const combinedOpenApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Climate Twin API",
    version: "2.0.0",
    description: "Local-first API for house layouts, environmental telemetry, forecasts, alerts, replay, and integrations.",
  },
  servers: [{ url: "/api/v1", description: "Legacy climate tuple API" }, { url: "/api/v2", description: "Registry-driven measurements API" }],
  tags: [
    { name: "Telemetry" }, { name: "Digital twin" }, { name: "Alerts" },
    { name: "Context" }, { name: "Weather" }, { name: "Integrations" }, { name: "Testing" }, { name: "Measurements" },
  ],
  paths: {
    "/health": { get: { operationId: "health", responses: { "200": { description: "Service health" } } } },
    "/openapi.json": { get: { operationId: "openApiDocument", responses: { "200": { description: "OpenAPI 3.1 document" } } } },
    "/measurement-definitions": {
      get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "listMeasurementDefinitions", parameters: [{ name: "includeDisabled", in: "query", schema: { type: "boolean", default: true }, description: "Set false to return enabled definitions only." }], responses: { "200": { description: "Measurement registry", content: { "application/json": { schema: { type: "object", required: ["definitions"], properties: { definitions: { type: "array", items: { $ref: "#/components/schemas/MeasurementDefinition" } } } } } } } } },
      post: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "createMeasurementDefinition", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/MeasurementDefinitionInput" } } } }, responses: { "201": { description: "Created definition" }, "409": { description: "Identifier already exists" } } },
    },
    "/measurement-definitions/{id}": {
      patch: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "updateMeasurementDefinition", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/MeasurementDefinitionPatch" } } } }, responses: { "200": { description: "Updated definition" }, "409": { description: "Immutable identifier, builtin status, or in-use canonical unit" } } },
      delete: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "disableMeasurementDefinition", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Definition disabled without orphaning samples or rules" } } },
    },
    "/measurements": {
      post: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "ingestMeasurements", security: [{ ingestKey: [] }], requestBody: { required: true, content: { "application/json": { schema: { oneOf: [{ $ref: "#/components/schemas/MeasurementSample" }, { type: "array", minItems: 1, maxItems: 1000, items: { $ref: "#/components/schemas/MeasurementSample" } }, { type: "object", required: ["sample"], properties: { sample: { $ref: "#/components/schemas/MeasurementSample" } } }, { type: "object", required: ["samples"], properties: { samples: { type: "array", minItems: 1, maxItems: 1000, items: { $ref: "#/components/schemas/MeasurementSample" } } } }] } } } }, responses: { "201": { description: "Atomically accepted unique samples" }, "422": { description: "Unit or value range mismatch" } } },
    },
    "/measurements/snapshot": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "measurementSnapshot", parameters: [{ name: "houseId", in: "query", schema: { type: "string" } }], responses: { "200": { description: "Latest sample for every sensor/metric pair", content: { "application/json": { schema: { type: "object", required: ["snapshot"], properties: { snapshot: { type: "array", items: { $ref: "#/components/schemas/MeasurementSnapshotEntry" } } } } } } } } } },
    "/measurements/history": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "measurementHistory", parameters: [{ name: "sensorId", in: "query", required: true, schema: { type: "string" } }, { name: "metric", in: "query", required: true, schema: { type: "string" } }, { name: "from", in: "query", schema: { type: "string", format: "date-time" } }, { name: "to", in: "query", schema: { type: "string", format: "date-time" } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 50000 } }], responses: { "200": { description: "Ordered independent metric samples", content: { "application/json": { schema: { type: "object", required: ["samples"], properties: { samples: { type: "array", items: { $ref: "#/components/schemas/MeasurementSample" } } } } } } } } } },
    "/measurements/events": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "streamMeasurements", parameters: [{ name: "sensorId", in: "query", style: "form", explode: true, schema: { type: "array", items: { type: "string" } }, description: "Repeat or comma-separate sensor IDs." }, { name: "metric", in: "query", style: "form", explode: true, schema: { type: "array", items: { type: "string" } }, description: "Repeat or comma-separate metric IDs." }], responses: { "200": { description: "Server-sent `measurement` events", content: { "text/event-stream": {} } } } } },
    "/measurements/forecast": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "forecastMeasurement", parameters: [{ name: "sensorId", in: "query", required: true, schema: { type: "string" } }, { name: "metric", in: "query", required: true, schema: { type: "string" } }, { name: "hours", in: "query", schema: { type: "integer", minimum: 1, maximum: 168, default: 12 } }], responses: { "200": { description: "Generic forecast", content: { "application/json": { schema: { type: "object", required: ["forecast"], properties: { forecast: { type: "array", items: { $ref: "#/components/schemas/MeasurementForecastPoint" } } } } } } }, "422": { description: "FORECAST_UNSUPPORTED" } } } },
    "/houses": {
      get: { tags: ["Digital twin"], operationId: "listHouses", responses: { "200": { description: "Houses", content: { "application/json": { schema: { type: "object", required: ["houses"], properties: { houses: { type: "array", items: { $ref: "#/components/schemas/House" } } } } } } } } },
      post: { tags: ["Digital twin"], operationId: "createHouse", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/HouseCreate" } } } }, responses: { "201": { description: "Created house", content: { "application/json": { schema: { type: "object", required: ["house"], properties: { house: { $ref: "#/components/schemas/House" } } } } } }, "400": { description: "Malformed house, location, or orientation" }, "422": { description: "Location is outside WGS84 bounds, its label is too long, or orientation is outside [0, 360)" } } },
    },
    "/houses/{id}": {
      get: { tags: ["Digital twin"], operationId: "getHouse", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "House", content: { "application/json": { schema: { type: "object", required: ["house"], properties: { house: { $ref: "#/components/schemas/House" } } } } } }, "404": { $ref: "#/components/responses/NotFound" } } },
      patch: { tags: ["Digital twin"], operationId: "updateHouse", description: "Partially updates house metadata, layout, WGS84 location, and/or the floor plan's compass orientation. Set location or orientationDegrees to null to clear it; changing or removing location invalidates the in-memory weather cache.", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/HousePatch" } } } }, responses: { "200": { description: "Updated house", content: { "application/json": { schema: { type: "object", required: ["house"], properties: { house: { $ref: "#/components/schemas/House" } } } } } }, "400": { description: "Malformed patch, location, or orientation" }, "404": { $ref: "#/components/responses/NotFound" }, "409": { description: "Layout would orphan or exclude an existing sensor" }, "422": { description: "Location is outside WGS84 bounds, its label is too long, or orientation is outside [0, 360)" } } },
      delete: { tags: ["Digital twin"], operationId: "deleteHouse", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } },
    },
    "/houses/{id}/weather": {
      get: {
        tags: ["Weather"],
        operationId: "getHouseWeather",
        description: "Returns house-scoped FMI observations, point forecasts, and active CAP warnings. Components can fail independently; inspect unavailable and stale before using the result.",
        parameters: [
          { $ref: "#/components/parameters/Id" },
          { name: "hours", in: "query", description: "Requested point-forecast horizon in hours.", schema: { type: "integer", minimum: 1, maximum: 240, default: 48 } },
        ],
        responses: {
          "200": { description: "FMI weather context, possibly partial or served from stale in-memory cache", content: { "application/json": { schema: { type: "object", required: ["weather"], properties: { weather: { $ref: "#/components/schemas/HouseWeather" } } } } } },
          "404": { $ref: "#/components/responses/NotFound" },
          "409": { description: "HOUSE_LOCATION_REQUIRED: set the house WGS84 location first" },
          "503": { description: "WEATHER_UNAVAILABLE: no usable FMI result or cached fallback is available" },
        },
      },
    },
    "/houses/{id}/layout": {
      put: { tags: ["Digital twin"], operationId: "replaceHouseLayout", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Updated house" }, "409": { description: "Layout would orphan or exclude an existing sensor" } } },
    },
    "/houses/{id}/floors/{floorId}": {
      put: { tags: ["Digital twin"], operationId: "replaceFloor", parameters: [{ $ref: "#/components/parameters/Id" }, { name: "floorId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Updated floor" }, "409": { description: "Floor change would orphan or exclude an existing sensor" } } },
    },
    "/sensors": {
      get: { tags: ["Digital twin"], operationId: "listSensors", responses: { "200": { description: "Sensors" } } },
      post: { tags: ["Digital twin"], operationId: "createSensor", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SensorInput" } } } }, responses: { "201": { description: "Created sensor" }, "404": { description: "House not found" }, "422": { description: "Floor membership or x/y bounds are invalid" } } },
    },
    "/sensors/snapshots": { get: { tags: ["Telemetry"], operationId: "listSensorSnapshots", responses: { "200": { description: "Sensors with latest readings" } } } },
    "/snapshot": { get: { tags: ["Telemetry"], operationId: "listSnapshotCompatibility", responses: { "200": { description: "Web-compatible sensor snapshots" } } } },
    "/sensors/{id}": {
      get: { tags: ["Digital twin"], operationId: "getSensor", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Sensor" } } },
      put: { tags: ["Digital twin"], operationId: "replaceSensorFields", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SensorPatch" } } } }, responses: { "200": { description: "Updated sensor" }, "404": { description: "Sensor or target house not found" }, "422": { description: "Target floor membership or x/y bounds are invalid" } } },
      patch: { tags: ["Digital twin"], operationId: "updateSensor", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SensorPatch" } } } }, responses: { "200": { description: "Updated sensor" }, "404": { description: "Sensor or target house not found" }, "422": { description: "Target floor membership or x/y bounds are invalid" } } },
      delete: { tags: ["Digital twin"], operationId: "deleteSensor", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } },
    },
    "/readings": {
      get: { tags: ["Telemetry"], operationId: "queryReadingsCompatibility", responses: { "200": { description: "Flat historical readings" } } },
      post: { tags: ["Telemetry"], operationId: "ingestReadings", security: [{ ingestKey: [] }], responses: { "201": { description: "Accepted readings and duplicate count" } } },
    },
    "/readings/latest": { get: { tags: ["Telemetry"], operationId: "latestReadings", responses: { "200": { description: "Latest reading per sensor" } } } },
    "/history": { get: { tags: ["Telemetry"], operationId: "queryHistory", responses: { "200": { description: "Historical series" } } } },
    "/forecast": { get: { tags: ["Telemetry"], operationId: "forecast", responses: { "200": { description: "Linear baseline forecasts with confidence bands" } } } },
    "/stream": { get: { tags: ["Telemetry"], operationId: "streamTelemetry", responses: { "200": { description: "Server-sent reading, alert, integration, and heartbeat events", content: { "text/event-stream": {} } } } } },
    "/events": { get: { tags: ["Telemetry"], operationId: "streamTelemetryCompatibility", responses: { "200": { description: "Web-compatible server-sent event stream", content: { "text/event-stream": {} } } } } },
    "/alert-rules": { get: { tags: ["Alerts"], operationId: "listAlertRules", responses: { "200": { description: "Rules" } } }, post: { tags: ["Alerts"], operationId: "createAlertRule", responses: { "201": { description: "Created rule" } } } },
    "/alert-rules/{id}": { patch: { tags: ["Alerts"], operationId: "updateAlertRule", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Updated rule" } } }, delete: { tags: ["Alerts"], operationId: "deleteAlertRule", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } } },
    "/alert-events": { get: { tags: ["Alerts"], operationId: "listAlertEvents", responses: { "200": { description: "Alert events" } } } },
    "/alert-events/{id}/acknowledge": { post: { tags: ["Alerts"], operationId: "acknowledgeAlert", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Acknowledged alert" } } } },
    "/alerts": { get: { tags: ["Alerts"], operationId: "listAlertsCompatibility", responses: { "200": { description: "Web-compatible alert events" } } } },
    "/alerts/{id}/acknowledge": { post: { tags: ["Alerts"], operationId: "acknowledgeAlertCompatibility", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Acknowledged alert" } } } },
    "/observations": { get: { tags: ["Context"], operationId: "listObservations", responses: { "200": { description: "Manual observations" } } }, post: { tags: ["Context"], operationId: "createObservation", responses: { "201": { description: "Created observation" } } } },
    "/observations/{id}": { delete: { tags: ["Context"], operationId: "deleteObservation", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } } },
    "/parameters": { get: { tags: ["Context"], operationId: "listStaticParameters", responses: { "200": { description: "Static parameters" } } }, post: { tags: ["Context"], operationId: "upsertStaticParameter", responses: { "200": { description: "Saved parameter" } } } },
    "/parameters/{id}": { delete: { tags: ["Context"], operationId: "deleteStaticParameter", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } } },
    "/static-parameters": { get: { tags: ["Context"], operationId: "listStaticParametersCompatibility", responses: { "200": { description: "Web-compatible static parameters" } } }, post: { tags: ["Context"], operationId: "saveStaticParameterCompatibility", responses: { "201": { description: "Saved parameter" } } } },
    "/assets": { get: { tags: ["Digital twin"], operationId: "listAssets", responses: { "200": { description: "Floor plan and 3D asset metadata" } } }, post: { tags: ["Digital twin"], operationId: "uploadAsset", responses: { "201": { description: "Uploaded base64 asset" } } } },
    "/assets/{id}": { get: { tags: ["Digital twin"], operationId: "downloadAsset", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Asset bytes" } } }, delete: { tags: ["Digital twin"], operationId: "deleteAsset", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } } },
    "/integrations/status": { get: { tags: ["Integrations"], operationId: "integrationStatus", responses: { "200": { description: "Redacted integration status" } } } },
    "/integrations/home-assistant/setup": { get: { tags: ["Integrations"], operationId: "homeAssistantSetup", responses: { "200": { description: "Environment and entity-map setup help" } } } },
    "/integrations/home-assistant/test": { post: { tags: ["Integrations"], operationId: "homeAssistantStatusTest", responses: { "200": { description: "Status of the environment-configured bridge" } } } },
    "/mock/scenarios": { get: { tags: ["Testing"], operationId: "listMockScenarios", responses: { "200": { description: "Scenarios" } } } },
    "/mock/scenario": { put: { tags: ["Testing"], operationId: "selectMockScenario", responses: { "200": { description: "Selected scenario" } } }, post: { tags: ["Testing"], operationId: "selectMockScenarioCompatibility", responses: { "200": { description: "Selected scenario" } } } },
    "/mock/tick": { post: { tags: ["Testing"], operationId: "generateMockTick", responses: { "201": { description: "Generated readings" } } } },
    "/replay": { get: { tags: ["Testing"], operationId: "replayStatus", responses: { "200": { description: "Replay state" } } }, post: { tags: ["Testing"], operationId: "startReplay", responses: { "202": { description: "Replay started" } } }, delete: { tags: ["Testing"], operationId: "stopReplay", responses: { "200": { description: "Replay stopped" } } } },
  },
  components: {
    securitySchemes: {
      ingestKey: { type: "apiKey", in: "header", name: "X-API-Key", description: "Optional, configured by INGEST_API_KEY." },
    },
    parameters: {
      Id: { name: "id", in: "path", required: true, schema: { type: "string" } },
    },
    schemas: {
      MeasurementDefinition: {
        type: "object",
        required: ["id", "labels", "unit", "precision", "validMin", "validMax", "displayMin", "displayMax", "interpolationDelta", "colorScale", "builtin", "enabled", "spatialInterpolation", "forecastSupported"],
        properties: {
          id: { type: "string", pattern: "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$", maxLength: 64 },
          labels: { type: "object", minProperties: 1, additionalProperties: { type: "string", minLength: 1 } },
          unit: { type: "string", minLength: 1 }, precision: { type: "integer", minimum: 0, maximum: 6 },
          validMin: { type: ["number", "null"] }, validMax: { type: ["number", "null"] },
          displayMin: { type: ["number", "null"] }, displayMax: { type: ["number", "null"] },
          interpolationDelta: { type: "number", exclusiveMinimum: 0 },
          colorScale: { enum: ["thermal", "humidity", "air-quality", "sequential"] },
          builtin: { type: "boolean", readOnly: true }, enabled: { type: "boolean" },
          spatialInterpolation: { type: "boolean" }, forecastSupported: { type: "boolean" },
        },
      },
      MeasurementDefinitionInput: {
        description: "Custom definitions default to enabled, sequential color, and no spatial interpolation or forecast capability.",
        type: "object",
        required: ["id", "labels", "unit"],
        properties: {
          id: { type: "string", pattern: "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$", maxLength: 64 },
          labels: { type: "object", minProperties: 1, additionalProperties: { type: "string", minLength: 1 } },
          unit: { type: "string", minLength: 1 }, precision: { type: "integer", minimum: 0, maximum: 6, default: 1 },
          validMin: { type: ["number", "null"], default: null }, validMax: { type: ["number", "null"], default: null },
          displayMin: { type: ["number", "null"], default: null }, displayMax: { type: ["number", "null"], default: null },
          interpolationDelta: { type: "number", exclusiveMinimum: 0, default: 1 },
          colorScale: { enum: ["thermal", "humidity", "air-quality", "sequential"], default: "sequential" },
          enabled: { type: "boolean", default: true }, spatialInterpolation: { type: "boolean", default: false }, forecastSupported: { type: "boolean", default: false },
        },
      },
      MeasurementDefinitionPatch: {
        type: "object",
        description: "Partial mutable definition fields. id and builtin are immutable.",
        properties: {
          labels: { type: "object", minProperties: 1, additionalProperties: { type: "string", minLength: 1 } },
          unit: { type: "string", minLength: 1 }, precision: { type: "integer", minimum: 0, maximum: 6 },
          validMin: { type: ["number", "null"] }, validMax: { type: ["number", "null"] },
          displayMin: { type: ["number", "null"] }, displayMax: { type: ["number", "null"] },
          interpolationDelta: { type: "number", exclusiveMinimum: 0 },
          colorScale: { enum: ["thermal", "humidity", "air-quality", "sequential"] },
          enabled: { type: "boolean" }, spatialInterpolation: { type: "boolean" }, forecastSupported: { type: "boolean" },
        },
      },
      MeasurementSample: {
        type: "object",
        required: ["sensorId", "metric", "value", "canonicalUnit", "timestamp", "source", "quality"],
        properties: {
          sensorId: { type: "string" }, metric: { type: "string" }, value: { type: "number" }, canonicalUnit: { type: "string" },
          timestamp: { type: "string", format: "date-time" }, source: { enum: ["mock", "home-assistant", "api", "replay"] },
          quality: { enum: ["good", "estimated", "stale"] },
        },
      },
      MeasurementForecastPoint: {
        type: "object",
        required: ["sensorId", "metric", "timestamp", "value", "low", "high"],
        properties: { sensorId: { type: "string" }, metric: { type: "string" }, timestamp: { type: "string", format: "date-time" }, value: { type: "number" }, low: { type: "number" }, high: { type: "number" } },
      },
      MeasurementSnapshotEntry: {
        type: "object",
        required: ["sensorId", "measurements"],
        properties: { sensorId: { type: "string" }, measurements: { type: "object", additionalProperties: { $ref: "#/components/schemas/MeasurementSample" } } },
      },
      Point: {
        type: "object",
        required: ["x", "y"],
        properties: {
          x: { type: "number", description: "Horizontal coordinate in the floor plan's width coordinate system." },
          y: { type: "number", description: "Depth coordinate in the floor plan's height coordinate system." },
        },
      },
      HouseLocation: {
        type: "object",
        description: "House position in the WGS84 latitude/longitude coordinate reference system. This is outdoor-context metadata, separate from floor-local x/y/z coordinates.",
        required: ["latitude", "longitude"],
        properties: {
          latitude: { type: "number", minimum: -90, maximum: 90, description: "WGS84 latitude in decimal degrees." },
          longitude: { type: "number", minimum: -180, maximum: 180, description: "WGS84 longitude in decimal degrees." },
          label: { type: "string", maxLength: 200, description: "Optional user-facing area label. A precise street address is not required." },
        },
      },
      Floor: {
        type: "object",
        required: ["id", "name", "width", "height", "elevation", "walls", "rooms"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          width: { type: "number", exclusiveMinimum: 0 },
          height: { type: "number", exclusiveMinimum: 0 },
          elevation: { type: "number", description: "Absolute floor-plane height in metres in the house vertical coordinate system; sensor z values use the same vertical origin." },
          walls: { type: "array", items: { type: "object", required: ["id", "from", "to"], properties: { id: { type: "string" }, from: { $ref: "#/components/schemas/Point" }, to: { $ref: "#/components/schemas/Point" } } } },
          rooms: { type: "array", items: { type: "object" } },
          backgroundImage: { type: "string", description: "Optional trusted raster data URL used by the local floor-plan editor." },
        },
      },
      House: {
        type: "object",
        required: ["id", "name", "timezone", "floors", "createdAt", "updatedAt"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          timezone: { type: "string", description: "IANA timezone used for display and calendar grouping; weather timestamps remain UTC ISO 8601." },
          location: { $ref: "#/components/schemas/HouseLocation" },
          orientationDegrees: { type: "number", minimum: 0, exclusiveMaximum: 360, description: "Confirmed clockwise compass bearing of the floor plan's top/up direction: 0=north, 90=east, 180=south, 270=west. Omitted while unknown." },
          floors: { type: "array", items: { $ref: "#/components/schemas/Floor" } },
          createdAt: { type: "string", format: "date-time", readOnly: true },
          updatedAt: { type: "string", format: "date-time", readOnly: true },
        },
      },
      HouseCreate: {
        type: "object",
        required: ["name", "timezone", "floors"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          timezone: { type: "string" },
          location: { $ref: "#/components/schemas/HouseLocation" },
          orientationDegrees: { type: "number", minimum: 0, exclusiveMaximum: 360, description: "Confirmed clockwise compass bearing of the floor plan's top/up direction. Omit while unknown." },
          floors: { type: "array", items: { $ref: "#/components/schemas/Floor" } },
        },
      },
      HousePatch: {
        type: "object",
        description: "Partial house update. Use location: null to remove weather location metadata.",
        properties: {
          name: { type: "string" },
          timezone: { type: "string" },
          location: { oneOf: [{ $ref: "#/components/schemas/HouseLocation" }, { type: "null" }] },
          orientationDegrees: { oneOf: [{ type: "number", minimum: 0, exclusiveMaximum: 360 }, { type: "null" }], description: "Confirmed clockwise compass bearing of the floor plan's top/up direction. Set null to return to unknown." },
          floors: { type: "array", items: { $ref: "#/components/schemas/Floor" } },
        },
      },
      OutdoorConditions: {
        type: "object",
        description: "Canonical outdoor observation or forecast values. Properties absent from the FMI response are omitted rather than inferred or converted to zero.",
        required: ["timestamp"],
        properties: {
          timestamp: { type: "string", format: "date-time" },
          temperatureC: { type: "number", description: "Air temperature in degrees Celsius." },
          dewPointC: { type: "number", description: "Dew point in degrees Celsius." },
          relativeHumidityPercent: { type: "number", description: "Relative humidity in percent." },
          pressureHpa: { type: "number", description: "Sea-level pressure in hectopascals." },
          windDirectionDegrees: { type: "number", description: "Wind direction in degrees." },
          windSpeedMps: { type: "number", description: "Wind speed in metres per second." },
          windGustMps: { type: "number", description: "Wind gust in metres per second." },
          precipitation1hMm: { type: "number", description: "One-hour precipitation in millimetres." },
          precipitationIntensityMmPerHour: { type: "number", description: "Observed precipitation intensity in millimetres per hour." },
          precipitationProbabilityPercent: { type: "number" },
          precipitationFormCode: { type: "number", description: "FMI precipitation-form code; clients must use FMI code metadata rather than invent labels." },
          potentialPrecipitationFormCode: { type: "number", description: "FMI potential precipitation-form code." },
          snowDepthCm: { type: "number", description: "Observed snow depth in centimetres." },
          cloudCoverPercent: { type: "number" },
          lowCloudCoverPercent: { type: "number" },
          mediumCloudCoverPercent: { type: "number" },
          highCloudCoverPercent: { type: "number" },
          visibilityMeters: { type: "number" },
          fogIntensity: { type: "number", description: "FMI fog-intensity value." },
          globalRadiationWm2: { type: "number", description: "Global solar radiation in watts per square metre." },
          weatherSymbolCode: { type: "number", description: "FMI WeatherSymbol3 code." },
          presentWeatherCode: { type: "number", description: "Observed FMI/WMO present-weather code." },
          thunderstormProbabilityPercent: { type: "number" },
          frostProbabilityPercent: { type: "number" },
          severeFrostProbabilityPercent: { type: "number" },
          maximumWindSpeedMps: { type: "number", description: "Hourly maximum wind speed in metres per second." },
          maximumWindGustMps: { type: "number", description: "Hourly maximum gust in metres per second." },
        },
      },
      WeatherStation: {
        type: "object",
        description: "Provenance for the nearest recent FMI observation station selected by the service. It is not the house position.",
        required: ["id", "name", "latitude", "longitude", "distanceKm"],
        properties: {
          id: { type: ["string", "null"] },
          name: { type: "string" },
          latitude: { type: "number" },
          longitude: { type: "number" },
          distanceKm: { type: "number", minimum: 0 },
        },
      },
      WeatherWarning: {
        type: "object",
        description: "An actual, non-cancelled FMI CAP warning whose polygon or circle contains the stored house location.",
        required: ["id", "event", "headline", "description", "severity", "urgency", "certainty", "effectiveAt", "onsetAt", "expiresAt", "areas", "web"],
        properties: {
          id: { type: "string" },
          event: { type: "string" },
          headline: { type: "string" },
          description: { type: "string" },
          severity: { enum: ["minor", "moderate", "severe", "extreme", "unknown"] },
          urgency: { type: "string" },
          certainty: { type: "string" },
          effectiveAt: { type: ["string", "null"], format: "date-time" },
          onsetAt: { type: ["string", "null"], format: "date-time" },
          expiresAt: { type: ["string", "null"], format: "date-time" },
          areas: { type: "array", items: { type: "string" } },
          web: { type: ["string", "null"], format: "uri" },
        },
      },
      HouseWeather: {
        type: "object",
        description: "House-scoped FMI observation, point forecast, and official-warning context. Inspect provenance, stale, and unavailable before decisions.",
        required: ["houseId", "location", "provider", "attribution", "fetchedAt", "forecastIssuedAt", "stale", "current", "observationStation", "forecast", "warnings", "unavailable"],
        properties: {
          houseId: { type: "string" },
          location: { $ref: "#/components/schemas/HouseLocation" },
          provider: { type: "string", enum: ["fmi"] },
          attribution: { type: "string", description: "Required FMI open-data attribution; preserve it in displays and downstream exports." },
          fetchedAt: { type: "string", format: "date-time", description: "Time the upstream fetch represented by this object began." },
          forecastIssuedAt: { type: ["string", "null"], format: "date-time", description: "FMI result time for the edited forecast, when available." },
          stale: { type: "boolean", description: "True when an upstream refresh failed and the service returned its previous in-memory result." },
          current: { oneOf: [{ $ref: "#/components/schemas/OutdoorConditions" }, { type: "null" }] },
          observationStation: { oneOf: [{ $ref: "#/components/schemas/WeatherStation" }, { type: "null" }] },
          forecast: { type: "array", items: { $ref: "#/components/schemas/OutdoorConditions" } },
          warnings: { type: "array", items: { $ref: "#/components/schemas/WeatherWarning" } },
          unavailable: { type: "array", uniqueItems: true, items: { enum: ["observation", "forecast", "short-range", "warnings"] }, description: "Upstream components that failed or returned no usable values. Empty arrays in a partial response must be interpreted with this field." },
        },
      },
      SensorInput: {
        type: "object",
        required: ["houseId", "floorId", "name", "room", "model", "x", "y", "z"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" }, floorId: { type: "string" },
          name: { type: "string" }, room: { type: "string" }, model: { type: "string" },
          x: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the selected floor width." },
          y: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the selected floor height." },
          z: { type: "number", description: "Unbounded absolute sensor height in metres using the same vertical origin as Floor.elevation; it may be below or above the floor plane." },
          tags: { type: "array", items: { type: "string" } }, enabled: { type: "boolean", default: true },
          temperatureEntityId: { type: "string" }, humidityEntityId: { type: "string" }, batteryEntityId: { type: "string" },
          measurementEntityIds: { type: "object", additionalProperties: { type: "string" } },
        },
      },
      SensorPatch: {
        type: "object",
        description: "Partial sensor update. A house/floor move and its coordinates are validated together before one atomic update.",
        properties: {
          houseId: { type: "string" }, floorId: { type: "string" },
          name: { type: "string" }, room: { type: "string" }, model: { type: "string" },
          x: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the resulting floor width." },
          y: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the resulting floor height." },
          z: { type: "number", description: "Unbounded absolute height in metres; negative and above-floor values are valid." },
          tags: { type: "array", items: { type: "string" } }, enabled: { type: "boolean" },
          temperatureEntityId: { type: "string" }, humidityEntityId: { type: "string" }, batteryEntityId: { type: "string" },
          measurementEntityIds: { type: "object", additionalProperties: { type: "string" } },
        },
      },
    },
    responses: {
      NotFound: { description: "Resource not found" },
    },
  },
} as const;

const V2_PATHS = new Set([
  "/measurement-definitions",
  "/measurement-definitions/{id}",
  "/measurements",
  "/measurements/snapshot",
  "/measurements/history",
  "/measurements/events",
  "/measurements/forecast",
]);

function selectPaths(version: "v1" | "v2"): Record<string, unknown> {
  return Object.fromEntries(Object.entries(combinedOpenApiDocument.paths).filter(([path]) =>
    path === "/openapi.json" || (version === "v2" ? V2_PATHS.has(path) : !V2_PATHS.has(path))));
}

export const openApiV1Document = {
  ...combinedOpenApiDocument,
  info: { ...combinedOpenApiDocument.info, version: "1.0.0", description: "Climate Twin v1 compatibility API for layouts, house-scoped FMI weather, and temperature/humidity tuples." },
  servers: [{ url: "/api/v1", description: "Legacy climate tuple API" }],
  paths: selectPaths("v1"),
};

export const openApiV2Document = {
  ...combinedOpenApiDocument,
  info: { ...combinedOpenApiDocument.info, version: "2.0.0", description: "Climate Twin v2 registry-driven sparse measurements API." },
  servers: [{ url: "/api/v2", description: "Registry-driven measurements API" }],
  paths: selectPaths("v2"),
};

/** @deprecated Import the version-specific document. Retained for source compatibility. */
export const openApiDocument = openApiV1Document;
