const combinedOpenApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Stuga Local API",
    version: "2.0.0",
    description: "Local-first Stuga API for house layouts, environmental telemetry, forecasts, alerts, replay, and integrations.",
  },
  servers: [{ url: "/api/v1", description: "Legacy climate tuple API" }, { url: "/api/v2", description: "Registry-driven measurements API" }],
  tags: [
    { name: "Telemetry" }, { name: "Digital twin" }, { name: "Alerts" },
    { name: "Context" }, { name: "Weather" }, { name: "Physics" }, { name: "Integrations" }, { name: "Testing" }, { name: "Measurements" },
  ],
  paths: {
    "/health": { get: { operationId: "health", responses: { "200": { description: "Service health", content: { "application/json": { schema: { type: "object", required: ["status", "systemVersion", "apiVersion", "database", "uptimeSeconds"], properties: { status: { const: "ok" }, systemVersion: { type: "string" }, apiVersion: { const: "v1" }, database: { const: "ready" }, uptimeSeconds: { type: "integer" } } } } } } } } },
    "/openapi.json": { get: { operationId: "openApiDocument", responses: { "200": { description: "OpenAPI 3.1 document", content: { "application/json": { schema: { type: "object" } } } } } } },
    "/locations/search": {
      get: {
        tags: ["Context"], operationId: "searchLocations",
        description: "Explicit, user-triggered worldwide place search. Returns coordinates and an IANA timezone so normal setup does not require manual latitude, longitude, or timezone entry.",
        parameters: [
          { name: "q", in: "query", required: true, schema: { type: "string", minLength: 2, maxLength: 120 } },
          { name: "language", in: "query", schema: { type: "string", pattern: "^[a-zA-Z]{2}$", default: "en" } },
        ],
        responses: {
          "200": { description: "Sanitized Open-Meteo/GeoNames place suggestions", content: { "application/json": { schema: { type: "object", required: ["results"], properties: { results: { type: "array", items: { $ref: "#/components/schemas/LocationSuggestion" } } } } } } },
          "400": { description: "Query is too short or too long" },
          "503": { description: "The location provider is temporarily unavailable" },
        },
      },
    },
    "/locations/defaults": {
      get: {
        tags: ["Context"], operationId: "coordinateDefaults",
        description: "Resolves an IANA timezone for explicitly supplied WGS84 coordinates. The browser calls this only after the user chooses device location.",
        parameters: [
          { name: "latitude", in: "query", required: true, schema: { type: "number", minimum: -90, maximum: 90 } },
          { name: "longitude", in: "query", required: true, schema: { type: "number", minimum: -180, maximum: 180 } },
        ],
        responses: {
          "200": { description: "Coordinate-derived defaults", content: { "application/json": { schema: { $ref: "#/components/schemas/CoordinateDefaults" } } } },
          "400": { description: "Both latitude and longitude are required" },
          "422": { description: "Invalid coordinates" },
          "503": { description: "Timezone discovery unavailable" },
        },
      },
    },
    "/measurement-definitions": {
      get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "listMeasurementDefinitions", parameters: [{ name: "includeDisabled", in: "query", schema: { type: "boolean", default: true }, description: "Set false to return enabled definitions only." }], responses: { "200": { description: "Measurement registry", content: { "application/json": { schema: { type: "object", required: ["definitions"], properties: { definitions: { type: "array", items: { $ref: "#/components/schemas/MeasurementDefinition" } } } } } } } } },
      post: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "createMeasurementDefinition", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/MeasurementDefinitionInput" } } } }, responses: { "201": { description: "Created definition", content: { "application/json": { schema: { type: "object", required: ["definition"], properties: { definition: { $ref: "#/components/schemas/MeasurementDefinition" } } } } } }, "409": { description: "Identifier already exists" } } },
    },
    "/measurement-definitions/{id}": {
      patch: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "updateMeasurementDefinition", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/MeasurementDefinitionPatch" } } } }, responses: { "200": { description: "Updated definition", content: { "application/json": { schema: { type: "object", required: ["definition"], properties: { definition: { $ref: "#/components/schemas/MeasurementDefinition" } } } } } }, "409": { description: "Immutable identifier, builtin status, or in-use canonical unit" } } },
      delete: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "disableMeasurementDefinition", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Definition disabled without orphaning samples or rules", content: { "application/json": { schema: { type: "object", required: ["definition"], properties: { definition: { $ref: "#/components/schemas/MeasurementDefinition" } } } } } } } },
    },
    "/measurements": {
      post: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "ingestMeasurements", security: [{ ingestKey: [] }], requestBody: { required: true, content: { "application/json": { schema: { oneOf: [{ $ref: "#/components/schemas/MeasurementSampleInput" }, { type: "array", minItems: 1, maxItems: 1000, items: { $ref: "#/components/schemas/MeasurementSampleInput" } }, { type: "object", required: ["sample"], properties: { sample: { $ref: "#/components/schemas/MeasurementSampleInput" } } }, { type: "object", required: ["samples"], properties: { samples: { type: "array", minItems: 1, maxItems: 1000, items: { $ref: "#/components/schemas/MeasurementSampleInput" } } } }] } } } }, responses: { "201": { description: "Atomically accepted unique samples", content: { "application/json": { schema: { type: "object", required: ["accepted", "samples"], properties: { accepted: { type: "integer" }, samples: { type: "array", items: { $ref: "#/components/schemas/MeasurementSample" } } } } } } }, "422": { description: "Unit or value range mismatch" } } },
    },
    "/measurements/import": {
      post: {
        servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "importHistoricalMeasurements",
        description: "Imports duplicate-safe historical samples without publishing live events, evaluating alert rules, or requiring sensors to be enabled.",
        security: [{ ingestKey: [] }],
        requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["samples"], properties: { samples: { type: "array", minItems: 1, maxItems: 10000, items: { $ref: "#/components/schemas/MeasurementSampleInput" } } } } } } },
        responses: { "201": { description: "Accepted unique samples and ignored duplicate count", content: { "application/json": { schema: { type: "object", required: ["accepted", "ignoredDuplicates"], properties: { accepted: { type: "integer" }, ignoredDuplicates: { type: "integer" } } } } } }, "422": { description: "Unit or value range mismatch" } },
      },
    },
    "/measurements/snapshot": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "measurementSnapshot", parameters: [{ name: "houseId", in: "query", schema: { type: "string" } }], responses: { "200": { description: "Latest sample for every sensor/metric pair", content: { "application/json": { schema: { type: "object", required: ["snapshot"], properties: { snapshot: { type: "array", items: { $ref: "#/components/schemas/MeasurementSnapshotEntry" } } } } } } } } } },
    "/measurements/history": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "measurementHistory", parameters: [{ name: "sensorId", in: "query", required: true, schema: { type: "string" } }, { name: "metric", in: "query", required: true, schema: { type: "string" } }, { name: "from", in: "query", schema: { type: "string", format: "date-time" } }, { name: "to", in: "query", schema: { type: "string", format: "date-time" } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 50000 } }], responses: { "200": { description: "Ordered independent metric samples", content: { "application/json": { schema: { type: "object", required: ["samples"], properties: { samples: { type: "array", items: { $ref: "#/components/schemas/MeasurementSample" } } } } } } } } } },
    "/measurements/events": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "streamMeasurements", parameters: [{ name: "sensorId", in: "query", style: "form", explode: true, schema: { type: "array", items: { type: "string" } }, description: "Repeat or comma-separate sensor IDs." }, { name: "metric", in: "query", style: "form", explode: true, schema: { type: "array", items: { type: "string" } }, description: "Repeat or comma-separate metric IDs." }], responses: { "200": { description: "Server-sent `measurement` events", content: { "text/event-stream": {} } } } } },
    "/measurements/forecast": { get: { servers: [{ url: "/api/v2" }], tags: ["Measurements"], operationId: "forecastMeasurement", parameters: [{ name: "sensorId", in: "query", required: true, schema: { type: "string" } }, { name: "metric", in: "query", required: true, schema: { type: "string" } }, { name: "hours", in: "query", schema: { type: "integer", minimum: 1, maximum: 168, default: 12 } }], responses: { "200": { description: "Generic forecast", content: { "application/json": { schema: { type: "object", required: ["forecast"], properties: { forecast: { type: "array", items: { $ref: "#/components/schemas/MeasurementForecastPoint" } } } } } } }, "422": { description: "FORECAST_UNSUPPORTED" } } } },
    "/houses": {
      get: { tags: ["Digital twin"], operationId: "listHouses", responses: { "200": { description: "Houses", content: { "application/json": { schema: { type: "object", required: ["houses"], properties: { houses: { type: "array", items: { $ref: "#/components/schemas/House" } } } } } } } } },
      post: { tags: ["Digital twin"], operationId: "createHouse", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/HouseCreate" } } } }, responses: { "201": { description: "Created house", content: { "application/json": { schema: { type: "object", required: ["house"], properties: { house: { $ref: "#/components/schemas/House" } } } } } }, "400": { description: "Malformed house, weather location, map placement, or orientation" }, "422": { description: "A timezone, coordinate, map scale, map footprint floor, location label, or orientation is invalid" } } },
    },
    "/houses/{id}": {
      get: { tags: ["Digital twin"], operationId: "getHouse", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "House", content: { "application/json": { schema: { type: "object", required: ["house"], properties: { house: { $ref: "#/components/schemas/House" } } } } } }, "404": { $ref: "#/components/responses/NotFound" } } },
      patch: { tags: ["Digital twin"], operationId: "updateHouse", description: "Partially updates house metadata, layout, weather location, precise map placement, and/or the floor plan's compass orientation. Set location, mapPlacement, or orientationDegrees to null to clear it. Map placement is independent of weather location and does not invalidate outdoor-temperature history.", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/HousePatch" } } } }, responses: { "200": { description: "Updated house", content: { "application/json": { schema: { type: "object", required: ["house"], properties: { house: { $ref: "#/components/schemas/House" } } } } } }, "400": { description: "Malformed patch, weather location, map placement, or orientation" }, "404": { $ref: "#/components/responses/NotFound" }, "409": { description: "Layout would orphan or exclude an existing sensor" }, "422": { description: "A timezone, coordinate, map scale, map footprint floor, location label, or orientation is invalid" } } },
      delete: { tags: ["Digital twin"], operationId: "deleteHouse", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } },
    },
    "/houses/{id}/weather": {
      get: {
        tags: ["Weather"],
        operationId: "getHouseWeather",
        description: "Returns provider-neutral house-scoped current conditions, point forecasts, and warning capability. Automatic routing uses FMI where Finnish official warning/observation coverage applies and Open-Meteo worldwide. Components can fail independently; inspect componentStatus (or the legacy unavailable field) and stale before using the result. An empty warnings array means no warnings only when componentStatus.warnings.emptyResultIsAuthoritative is true.",
        parameters: [
          { $ref: "#/components/parameters/Id" },
          { name: "hours", in: "query", description: "Requested point-forecast horizon in hours.", schema: { type: "integer", minimum: 1, maximum: 240, default: 48 } },
        ],
        responses: {
          "200": { description: "Weather context, possibly partial or served from stale in-memory cache", content: { "application/json": { schema: { type: "object", required: ["weather"], properties: { weather: { $ref: "#/components/schemas/HouseWeather" } } } } } },
          "404": { $ref: "#/components/responses/NotFound" },
          "409": { description: "HOUSE_LOCATION_REQUIRED: set the house WGS84 location first; or WEATHER_REQUEST_SUPERSEDED: house metadata changed while the upstream request was running" },
          "503": { description: "WEATHER_UNAVAILABLE: no usable provider result or cached fallback is available" },
        },
      },
    },
    "/houses/{id}/thermal-simulation": {
      get: {
        tags: ["Physics"],
        operationId: "runThermalSimulation",
        description: "Fits an effective sensor-scoped first-order thermal model from overlapping indoor and persisted outdoor observations, then returns distinct observed, simulated, residual, and optional weather-scenario values. Insufficient calibration data is a successful typed state; simulated values are never stored as measurements.",
        parameters: [
          { $ref: "#/components/parameters/Id" },
          { name: "sensorId", in: "query", required: true, schema: { type: "string" } },
          { name: "from", in: "query", schema: { type: "string", format: "date-time" }, description: "Calibration start; the requested range may not exceed 14 days." },
          { name: "to", in: "query", schema: { type: "string", format: "date-time" }, description: "Calibration end; defaults to now." },
          { name: "horizonHours", in: "query", schema: { type: "integer", minimum: 0, maximum: 72, default: 12 } },
          { name: "scenarioOutdoorTemperatureC", in: "query", schema: { type: "number" }, description: "Optional constant future outdoor boundary. This does not alter historical calibration." },
        ],
        responses: {
          "200": { description: "Ready, provisional, or insufficient-data thermal result", content: { "application/json": { schema: { type: "object", required: ["simulation"], properties: { simulation: { $ref: "#/components/schemas/ThermalSimulationResult" } } } } } },
          "400": { description: "Malformed timestamp, range, or scenario" },
          "404": { $ref: "#/components/responses/NotFound" },
          "409": { description: "The sensor belongs to another house" },
        },
      },
    },
    "/houses/{id}/layout": {
      put: {
        tags: ["Digital twin"], operationId: "replaceHouseLayout", parameters: [{ $ref: "#/components/parameters/Id" }],
        requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["floors"], properties: { floors: { type: "array", items: { $ref: "#/components/schemas/Floor" } } } } } } },
        responses: { "200": { description: "Updated house", content: { "application/json": { schema: { type: "object", required: ["house"], properties: { house: { $ref: "#/components/schemas/House" } } } } } }, "404": { $ref: "#/components/responses/NotFound" }, "409": { description: "Layout would orphan or exclude an existing sensor" } },
      },
    },
    "/houses/{id}/floors/{floorId}": {
      put: {
        tags: ["Digital twin"], operationId: "replaceFloor", parameters: [{ $ref: "#/components/parameters/Id" }, { name: "floorId", in: "path", required: true, schema: { type: "string" } }],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/Floor" } } } },
        responses: { "200": { description: "Updated floor", content: { "application/json": { schema: { $ref: "#/components/schemas/Floor" } } } }, "404": { $ref: "#/components/responses/NotFound" }, "409": { description: "Floor change would orphan or exclude an existing sensor" } },
      },
    },
    "/sensors": {
      get: { tags: ["Digital twin"], operationId: "listSensors", parameters: [{ $ref: "#/components/parameters/HouseIdQuery" }], responses: { "200": { description: "Sensors", content: { "application/json": { schema: { type: "object", required: ["sensors"], properties: { sensors: { type: "array", items: { $ref: "#/components/schemas/Sensor" } } } } } } } } },
      post: { tags: ["Digital twin"], operationId: "createSensor", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SensorInput" } } } }, responses: { "201": { description: "Created sensor", content: { "application/json": { schema: { type: "object", required: ["sensor"], properties: { sensor: { $ref: "#/components/schemas/Sensor" } } } } } }, "404": { description: "House not found" }, "409": { description: "TP-Link child device is already assigned" }, "422": { description: "Floor membership or x/y bounds are invalid" } } },
    },
    "/sensors/snapshots": { get: { tags: ["Telemetry"], operationId: "listSensorSnapshots", parameters: [{ $ref: "#/components/parameters/HouseIdQuery" }], responses: { "200": { description: "Sensors with latest readings", content: { "application/json": { schema: { type: "object", required: ["sensors"], properties: { sensors: { type: "array", items: { $ref: "#/components/schemas/SensorSnapshot" } } } } } } } } } },
    "/snapshot": { get: { tags: ["Telemetry"], operationId: "listSnapshotCompatibility", parameters: [{ $ref: "#/components/parameters/HouseIdQuery" }], responses: { "200": { description: "Web-compatible sensor snapshots", content: { "application/json": { schema: { type: "object", required: ["snapshot"], properties: { snapshot: { type: "array", items: { $ref: "#/components/schemas/SensorSnapshot" } } } } } } } } } },
    "/sensors/{id}": {
      get: { tags: ["Digital twin"], operationId: "getSensor", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Sensor", content: { "application/json": { schema: { type: "object", required: ["sensor", "reading"], properties: { sensor: { $ref: "#/components/schemas/Sensor" }, reading: { oneOf: [{ $ref: "#/components/schemas/Reading" }, { type: "null" }] } } } } } } } },
      put: { tags: ["Digital twin"], operationId: "replaceSensorFields", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SensorPatch" } } } }, responses: { "200": { description: "Updated sensor", content: { "application/json": { schema: { $ref: "#/components/schemas/Sensor" } } } }, "404": { description: "Sensor or target house not found" }, "409": { description: "TP-Link child device is already assigned" }, "422": { description: "Target floor membership or x/y bounds are invalid" } } },
      patch: { tags: ["Digital twin"], operationId: "updateSensor", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SensorPatch" } } } }, responses: { "200": { description: "Updated sensor", content: { "application/json": { schema: { type: "object", required: ["sensor"], properties: { sensor: { $ref: "#/components/schemas/Sensor" } } } } } }, "404": { description: "Sensor or target house not found" }, "409": { description: "TP-Link child device is already assigned" }, "422": { description: "Target floor membership or x/y bounds are invalid" } } },
      delete: { tags: ["Digital twin"], operationId: "deleteSensor", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } },
    },
    "/readings": {
      get: { tags: ["Telemetry"], operationId: "queryReadingsCompatibility", parameters: [{ $ref: "#/components/parameters/SensorIdsQuery" }, { $ref: "#/components/parameters/FromQuery" }, { $ref: "#/components/parameters/ToQuery" }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 50000, default: 2000 } }], responses: { "200": { description: "Flat historical readings", content: { "application/json": { schema: { type: "object", required: ["readings"], properties: { readings: { type: "array", items: { $ref: "#/components/schemas/Reading" } } } } } } } } },
      post: {
        tags: ["Telemetry"], operationId: "ingestReadings", security: [{ ingestKey: [] }],
        requestBody: { required: true, content: { "application/json": { schema: { oneOf: [{ $ref: "#/components/schemas/ReadingInput" }, { type: "array", minItems: 1, maxItems: 1000, items: { $ref: "#/components/schemas/ReadingInput" } }, { type: "object", required: ["readings"], properties: { readings: { type: "array", minItems: 1, maxItems: 1000, items: { $ref: "#/components/schemas/ReadingInput" } } } }] } } } },
        responses: { "201": { description: "Accepted readings and duplicate count", content: { "application/json": { schema: { type: "object", required: ["readings", "ignoredDuplicates"], properties: { readings: { type: "array", items: { $ref: "#/components/schemas/Reading" } }, ignoredDuplicates: { type: "integer" } } } } } } },
      },
    },
    "/readings/latest": { get: { tags: ["Telemetry"], operationId: "latestReadings", parameters: [{ $ref: "#/components/parameters/SensorIdsQuery" }], responses: { "200": { description: "Latest reading per sensor", content: { "application/json": { schema: { type: "object", required: ["readings"], properties: { readings: { type: "array", items: { $ref: "#/components/schemas/Reading" } } } } } } } } } },
    "/history": { get: { tags: ["Telemetry"], operationId: "queryHistory", parameters: [{ $ref: "#/components/parameters/SensorIdsQuery" }, { $ref: "#/components/parameters/FromQuery" }, { $ref: "#/components/parameters/ToQuery" }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 50000, default: 20000 } }, { name: "forecastHours", in: "query", schema: { type: "integer", minimum: 0, maximum: 168, default: 0 } }], responses: { "200": { description: "Historical series", content: { "application/json": { schema: { type: "object", required: ["from", "to", "series", "truncated"], properties: { from: { type: "string", format: "date-time" }, to: { type: "string", format: "date-time" }, series: { type: "array", items: { $ref: "#/components/schemas/HistorySeries" } }, truncated: { type: "boolean" } } } } } } } } },
    "/forecast": { get: { tags: ["Telemetry"], operationId: "forecast", parameters: [{ $ref: "#/components/parameters/SensorIdsQuery" }, { name: "hours", in: "query", schema: { type: "integer", minimum: 1, maximum: 168, default: 12 } }, { name: "horizonMinutes", in: "query", schema: { type: "integer", minimum: 0, maximum: 10080, default: 0 }, description: "Compatibility horizon; when greater than zero it takes precedence over hours." }], responses: { "200": { description: "Linear baseline forecasts with confidence bands", content: { "application/json": { schema: { type: "object", required: ["generatedAt", "model", "series"], properties: { generatedAt: { type: "string", format: "date-time" }, model: { const: "linear-v1" }, series: { type: "array", items: { type: "object", required: ["sensorId", "forecast"], properties: { sensorId: { type: "string" }, forecast: { type: "array", items: { $ref: "#/components/schemas/ForecastPoint" } } } } }, forecast: { type: "array", items: { $ref: "#/components/schemas/ForecastPoint" } } } } } } } } } },
    "/stream": { get: { tags: ["Telemetry"], operationId: "streamTelemetry", parameters: [{ $ref: "#/components/parameters/SensorIdsQuery" }], responses: { "200": { description: "Server-sent reading, alert, integration, and heartbeat events", content: { "text/event-stream": {} } } } } },
    "/events": { get: { tags: ["Telemetry"], operationId: "streamTelemetryCompatibility", parameters: [{ $ref: "#/components/parameters/SensorIdsQuery" }], responses: { "200": { description: "Web-compatible server-sent event stream", content: { "text/event-stream": {} } } } } },
    "/alert-rules": {
      get: { tags: ["Alerts"], operationId: "listAlertRules", responses: { "200": { description: "Rules", content: { "application/json": { schema: { type: "object", required: ["rules"], properties: { rules: { type: "array", items: { $ref: "#/components/schemas/AlertRule" } } } } } } } } },
      post: { tags: ["Alerts"], operationId: "createAlertRule", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AlertRuleInput" } } } }, responses: { "201": { description: "Created rule", content: { "application/json": { schema: { $ref: "#/components/schemas/AlertRule" } } } } } },
    },
    "/alert-rules/{id}": {
      patch: { tags: ["Alerts"], operationId: "updateAlertRule", parameters: [{ $ref: "#/components/parameters/Id" }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AlertRulePatch" } } } }, responses: { "200": { description: "Updated rule", content: { "application/json": { schema: { type: "object", required: ["rule"], properties: { rule: { $ref: "#/components/schemas/AlertRule" } } } } } } } },
      delete: { tags: ["Alerts"], operationId: "deleteAlertRule", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } },
    },
    "/alert-events": { get: { tags: ["Alerts"], operationId: "listAlertEvents", parameters: [{ name: "active", in: "query", schema: { type: "boolean", default: false } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 1000, default: 200 } }], responses: { "200": { description: "Alert events", content: { "application/json": { schema: { type: "object", required: ["events"], properties: { events: { type: "array", items: { $ref: "#/components/schemas/AlertEvent" } } } } } } } } } },
    "/alert-events/{id}/acknowledge": { post: { tags: ["Alerts"], operationId: "acknowledgeAlert", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Acknowledged alert", content: { "application/json": { schema: { type: "object", required: ["event"], properties: { event: { $ref: "#/components/schemas/AlertEvent" } } } } } } } } },
    "/alerts": { get: { tags: ["Alerts"], operationId: "listAlertsCompatibility", parameters: [{ name: "active", in: "query", schema: { type: "boolean", default: false } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 1000, default: 200 } }], responses: { "200": { description: "Web-compatible alert events", content: { "application/json": { schema: { type: "object", required: ["alerts"], properties: { alerts: { type: "array", items: { $ref: "#/components/schemas/AlertEvent" } } } } } } } } } },
    "/alerts/{id}/acknowledge": { post: { tags: ["Alerts"], operationId: "acknowledgeAlertCompatibility", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Acknowledged alert", content: { "application/json": { schema: { $ref: "#/components/schemas/AlertEvent" } } } } } } },
    "/observations": {
      get: { tags: ["Context"], operationId: "listObservations", parameters: [{ $ref: "#/components/parameters/HouseIdQuery" }], responses: { "200": { description: "Manual observations", content: { "application/json": { schema: { type: "object", required: ["observations"], properties: { observations: { type: "array", items: { $ref: "#/components/schemas/ManualObservation" } } } } } } } } },
      post: { tags: ["Context"], operationId: "createObservation", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ObservationInput" } } } }, responses: { "201": { description: "Created observation", content: { "application/json": { schema: { $ref: "#/components/schemas/ManualObservation" } } } } } },
    },
    "/observations/{id}": { delete: { tags: ["Context"], operationId: "deleteObservation", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } } },
    "/parameters": {
      get: { tags: ["Context"], operationId: "listStaticParameters", parameters: [{ $ref: "#/components/parameters/HouseIdQuery" }], responses: { "200": { description: "Static parameters", content: { "application/json": { schema: { type: "object", required: ["parameters"], properties: { parameters: { type: "array", items: { $ref: "#/components/schemas/StaticParameter" } } } } } } } } },
      post: { tags: ["Context"], operationId: "upsertStaticParameter", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/StaticParameterInput" } } } }, responses: { "200": { description: "Saved parameter", content: { "application/json": { schema: { type: "object", required: ["parameter"], properties: { parameter: { $ref: "#/components/schemas/StaticParameter" } } } } } } } },
    },
    "/parameters/{id}": { delete: { tags: ["Context"], operationId: "deleteStaticParameter", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } } },
    "/static-parameters": {
      get: { tags: ["Context"], operationId: "listStaticParametersCompatibility", parameters: [{ $ref: "#/components/parameters/HouseIdQuery" }], responses: { "200": { description: "Web-compatible static parameters", content: { "application/json": { schema: { type: "object", required: ["parameters"], properties: { parameters: { type: "array", items: { $ref: "#/components/schemas/StaticParameter" } } } } } } } } },
      post: { tags: ["Context"], operationId: "saveStaticParameterCompatibility", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/StaticParameterInput" } } } }, responses: { "201": { description: "Saved parameter", content: { "application/json": { schema: { $ref: "#/components/schemas/StaticParameter" } } } } } },
    },
    "/assets": {
      get: { tags: ["Digital twin"], operationId: "listAssets", parameters: [{ $ref: "#/components/parameters/HouseIdQuery" }], responses: { "200": { description: "Floor plan and 3D asset metadata", content: { "application/json": { schema: { type: "object", required: ["assets"], properties: { assets: { type: "array", items: { $ref: "#/components/schemas/Asset" } } } } } } } } },
      post: { tags: ["Digital twin"], operationId: "uploadAsset", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AssetUploadInput" } } } }, responses: { "201": { description: "Uploaded base64 asset", content: { "application/json": { schema: { type: "object", required: ["asset", "url"], properties: { asset: { $ref: "#/components/schemas/Asset" }, url: { type: "string" } } } } } }, "413": { description: "Decoded asset exceeds 10 MiB" }, "415": { description: "Unsupported asset media type" } } },
    },
    "/assets/{id}": { get: { tags: ["Digital twin"], operationId: "downloadAsset", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "200": { description: "Asset bytes", content: { "*/*": { schema: { type: "string", contentEncoding: "base64" } } } } } }, delete: { tags: ["Digital twin"], operationId: "deleteAsset", parameters: [{ $ref: "#/components/parameters/Id" }], responses: { "204": { description: "Deleted" } } } },
    "/integrations/status": { get: { tags: ["Integrations"], operationId: "integrationStatus", responses: { "200": { description: "Redacted integration status", content: { "application/json": { schema: { $ref: "#/components/schemas/IntegrationStatus" } } } } } } },
    "/integrations/discover": { post: { tags: ["Integrations"], operationId: "discoverIntegrations", responses: { "200": { description: "Best-effort LAN discovery results for Home Assistant and TP-Link H100/H200 hubs", content: { "application/json": { schema: { $ref: "#/components/schemas/IntegrationDiscoveryResult" } } } } } } },
    "/integrations/home-assistant/config": { put: { tags: ["Integrations"], operationId: "configureHomeAssistant", description: "Write-only server-side credential setup; responses never contain the saved URL or token.", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/HomeAssistantConfigInput" } } } }, responses: { "200": { description: "Credentials saved and connection started", content: { "application/json": { schema: { type: "object", required: ["ok", "configured", "integration"], properties: { ok: { const: true }, configured: { const: true }, integration: { $ref: "#/components/schemas/IntegrationStatus" } } } } } }, "400": { description: "Invalid URL or token" } } } },
    "/integrations/home-assistant/setup": { get: { tags: ["Integrations"], operationId: "homeAssistantSetup", responses: { "200": { description: "Environment and entity-map setup help", content: { "application/json": { schema: { type: "object", required: ["configured", "steps", "entityMapSchema", "notes"], additionalProperties: true } } } } } } },
    "/integrations/home-assistant/test": { post: { tags: ["Integrations"], operationId: "homeAssistantStatusTest", responses: { "200": { description: "Status of the environment-configured bridge", content: { "application/json": { schema: { $ref: "#/components/schemas/IntegrationTestResult" } } } } } } },
    "/integrations/tp-link/setup": { get: { tags: ["Integrations"], operationId: "tpLinkSetup", responses: { "200": { description: "Direct H100/H200 discovery and sensor-binding setup help", content: { "application/json": { schema: { type: "object", required: ["configured", "supportedHubs", "supportedClimateSensors", "steps", "sensorPatchSchema", "deviceMapSchema", "notes"], additionalProperties: true } } } } } } },
    "/integrations/tp-link/config": { put: { tags: ["Integrations"], operationId: "configureTpLink", description: "Write-only server-side credential setup; responses never contain account credentials.", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/TpLinkConfigInput" } } } }, responses: { "200": { description: "Credentials saved and connection started", content: { "application/json": { schema: { type: "object", required: ["ok", "configured", "integration"], properties: { ok: { const: true }, configured: { const: true }, integration: { $ref: "#/components/schemas/IntegrationStatus" } } } } } }, "400": { description: "Invalid hub address or credentials" } } } },
    "/integrations/tp-link/devices": { get: { tags: ["Integrations"], operationId: "listTpLinkDevices", responses: { "200": { description: "Sanitized child devices seen by the local hub bridge", content: { "application/json": { schema: { type: "object", required: ["devices"], properties: { devices: { type: "array", items: { $ref: "#/components/schemas/TpLinkDiscoveredDevice" } } } } } } } } } },
    "/integrations/tp-link/test": { post: { tags: ["Integrations"], operationId: "tpLinkStatusTest", responses: { "200": { description: "Status of the direct local TP-Link bridge", content: { "application/json": { schema: { $ref: "#/components/schemas/IntegrationTestResult" } } } } } } },
    "/mock/scenarios": { get: { tags: ["Testing"], operationId: "listMockScenarios", responses: { "200": { description: "Scenarios", content: { "application/json": { schema: { type: "object", required: ["scenarios", "active", "enabled"], properties: { scenarios: { type: "array", items: { $ref: "#/components/schemas/MockScenario" } }, active: { $ref: "#/components/schemas/MockScenarioId" }, enabled: { type: "boolean" } } } } } } } } },
    "/mock/scenario": {
      put: { tags: ["Testing"], operationId: "selectMockScenario", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["scenario"], properties: { scenario: { $ref: "#/components/schemas/MockScenarioId" } } } } } }, responses: { "200": { description: "Selected scenario", content: { "application/json": { schema: { type: "object", required: ["active"], properties: { active: { $ref: "#/components/schemas/MockScenarioId" } } } } } } } },
      post: { tags: ["Testing"], operationId: "selectMockScenarioCompatibility", requestBody: { required: true, content: { "application/json": { schema: { type: "object", properties: { scenarioId: { $ref: "#/components/schemas/MockScenarioId" }, scenario: { $ref: "#/components/schemas/MockScenarioId" } }, anyOf: [{ required: ["scenarioId"] }, { required: ["scenario"] }] } } } }, responses: { "200": { description: "Selected scenario", content: { "application/json": { schema: { type: "object", required: ["ok", "active"], properties: { ok: { const: true }, active: { $ref: "#/components/schemas/MockScenarioId" } } } } } } } },
    },
    "/mock/tick": { post: { tags: ["Testing"], operationId: "generateMockTick", responses: { "201": { description: "Generated readings", content: { "application/json": { schema: { type: "object", required: ["readings", "scenario"], properties: { readings: { type: "array", items: { $ref: "#/components/schemas/Reading" } }, scenario: { $ref: "#/components/schemas/MockScenarioId" } } } } } } } } },
    "/replay": {
      get: { tags: ["Testing"], operationId: "replayStatus", responses: { "200": { description: "Replay state", content: { "application/json": { schema: { type: "object", required: ["replay"], properties: { replay: { $ref: "#/components/schemas/ReplayState" } } } } } } } },
      post: { tags: ["Testing"], operationId: "startReplay", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReplayInput" } } } }, responses: { "202": { description: "Replay started", content: { "application/json": { schema: { type: "object", required: ["replay"], properties: { replay: { $ref: "#/components/schemas/ReplayState" } } } } } } } },
      delete: { tags: ["Testing"], operationId: "stopReplay", responses: { "200": { description: "Replay stopped", content: { "application/json": { schema: { type: "object", required: ["replay"], properties: { replay: { $ref: "#/components/schemas/ReplayState" } } } } } } } },
    },
  },
  components: {
    securitySchemes: {
      ingestKey: { type: "apiKey", in: "header", name: "X-API-Key", description: "Optional, configured by INGEST_API_KEY." },
    },
    parameters: {
      Id: { name: "id", in: "path", required: true, schema: { type: "string" } },
      HouseIdQuery: { name: "houseId", in: "query", schema: { type: "string" }, description: "Optional house scope." },
      SensorIdsQuery: { name: "sensorId", in: "query", style: "form", explode: true, schema: { type: "array", items: { type: "string" } }, description: "Repeat or comma-separate sensor IDs." },
      FromQuery: { name: "from", in: "query", schema: { type: "string", format: "date-time" } },
      ToQuery: { name: "to", in: "query", schema: { type: "string", format: "date-time" } },
    },
    schemas: {
      MeasurementDefinition: {
        type: "object",
        required: ["id", "labels", "unit", "precision", "validMin", "validMax", "displayMin", "displayMax", "interpolationDelta", "colorScale", "builtin", "enabled", "spatialInterpolation", "forecastSupported"],
        properties: {
          id: { type: "string", pattern: "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$", maxLength: 64 },
          labels: { type: "object", minProperties: 1, additionalProperties: { type: "string", minLength: 1 } },
          unit: { type: "string", minLength: 1 }, precision: { type: "integer", minimum: 0, maximum: 6 },
          validMin: { type: ["number", "null"] }, validMax: { type: ["number", "null"] },
          displayMin: { type: ["number", "null"] }, displayMax: { type: ["number", "null"] },
          interpolationDelta: { type: "number", exclusiveMinimum: 0 },
          colorScale: { enum: ["thermal", "humidity", "air-quality", "sequential"] },
          builtin: { type: "boolean", readOnly: true }, enabled: { type: "boolean" },
          spatialInterpolation: { type: "boolean" }, forecastSupported: { type: "boolean" },
        },
      },
      MeasurementDefinitionInput: {
        description: "Custom definitions default to enabled, sequential color, and no spatial interpolation or forecast capability.",
        type: "object",
        required: ["id", "labels", "unit"],
        properties: {
          id: { type: "string", pattern: "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$", maxLength: 64 },
          labels: { type: "object", minProperties: 1, additionalProperties: { type: "string", minLength: 1 } },
          unit: { type: "string", minLength: 1 }, precision: { type: "integer", minimum: 0, maximum: 6, default: 1 },
          validMin: { type: ["number", "null"], default: null }, validMax: { type: ["number", "null"], default: null },
          displayMin: { type: ["number", "null"], default: null }, displayMax: { type: ["number", "null"], default: null },
          interpolationDelta: { type: "number", exclusiveMinimum: 0, default: 1 },
          colorScale: { enum: ["thermal", "humidity", "air-quality", "sequential"], default: "sequential" },
          enabled: { type: "boolean", default: true }, spatialInterpolation: { type: "boolean", default: false }, forecastSupported: { type: "boolean", default: false },
        },
      },
      MeasurementDefinitionPatch: {
        type: "object",
        description: "Partial mutable definition fields. id and builtin are immutable.",
        properties: {
          labels: { type: "object", minProperties: 1, additionalProperties: { type: "string", minLength: 1 } },
          unit: { type: "string", minLength: 1 }, precision: { type: "integer", minimum: 0, maximum: 6 },
          validMin: { type: ["number", "null"] }, validMax: { type: ["number", "null"] },
          displayMin: { type: ["number", "null"] }, displayMax: { type: ["number", "null"] },
          interpolationDelta: { type: "number", exclusiveMinimum: 0 },
          colorScale: { enum: ["thermal", "humidity", "air-quality", "sequential"] },
          enabled: { type: "boolean" }, spatialInterpolation: { type: "boolean" }, forecastSupported: { type: "boolean" },
        },
      },
      MeasurementSampleInput: {
        type: "object",
        description: "Canonical unit, timestamp, source, and quality are optional on ingestion and receive registry/API defaults when omitted.",
        required: ["sensorId", "metric", "value"],
        properties: {
          sensorId: { type: "string" },
          metric: { type: "string" },
          value: { type: "number" },
          canonicalUnit: { type: "string", description: "Defaults to the registered canonical unit." },
          timestamp: { type: "string", format: "date-time", description: "Defaults to the server time. Live ingestion accepts at most five minutes of positive sender clock skew." },
          source: { enum: ["mock", "home-assistant", "tp-link", "api", "import", "replay"], default: "api" },
          quality: { enum: ["good", "estimated", "stale"], default: "good" },
        },
      },
      MeasurementSample: {
        type: "object",
        required: ["sensorId", "metric", "value", "canonicalUnit", "timestamp", "source", "quality"],
        properties: {
          sensorId: { type: "string" }, metric: { type: "string" }, value: { type: "number" }, canonicalUnit: { type: "string" },
          timestamp: { type: "string", format: "date-time" }, source: { enum: ["mock", "home-assistant", "tp-link", "api", "import", "replay"] },
          quality: { enum: ["good", "estimated", "stale"] },
        },
      },
      MeasurementForecastPoint: {
        type: "object",
        required: ["sensorId", "metric", "timestamp", "value", "low", "high"],
        properties: { sensorId: { type: "string" }, metric: { type: "string" }, timestamp: { type: "string", format: "date-time" }, value: { type: "number" }, low: { type: "number" }, high: { type: "number" } },
      },
      MeasurementSnapshotEntry: {
        type: "object",
        required: ["sensorId", "measurements"],
        properties: { sensorId: { type: "string" }, measurements: { type: "object", additionalProperties: { $ref: "#/components/schemas/MeasurementSample" } } },
      },
      ReadingInput: {
        type: "object",
        required: ["sensorId", "temperature", "humidity"],
        properties: {
          sensorId: { type: "string" },
          timestamp: { type: "string", format: "date-time", description: "Defaults to the server time. Live ingestion accepts at most five minutes of positive sender clock skew." },
          temperature: { type: "number", minimum: -80, maximum: 100 },
          humidity: { type: "number", minimum: 0, maximum: 100 },
          battery: { type: ["number", "null"], minimum: 0, maximum: 100, default: null },
          quality: { enum: ["good", "estimated", "stale"], default: "good" },
          measurements: { type: "object", additionalProperties: { type: "number" }, description: "Optional registry-defined numeric values accepted alongside the v1 tuple." },
        },
      },
      Reading: {
        type: "object",
        required: ["sensorId", "timestamp", "temperature", "humidity", "battery", "source", "quality"],
        properties: {
          sensorId: { type: "string" }, timestamp: { type: "string", format: "date-time" },
          temperature: { type: "number" }, humidity: { type: "number" }, battery: { type: ["number", "null"] },
          source: { enum: ["mock", "home-assistant", "tp-link", "api", "import", "replay"] },
          quality: { enum: ["good", "estimated", "stale"] },
          measurements: { type: "object", additionalProperties: { type: "number" } },
        },
      },
      ForecastPoint: {
        type: "object",
        required: ["sensorId", "timestamp", "temperature", "humidity", "temperatureLow", "temperatureHigh", "humidityLow", "humidityHigh"],
        properties: {
          sensorId: { type: "string" }, timestamp: { type: "string", format: "date-time" },
          temperature: { type: "number" }, humidity: { type: "number" },
          temperatureLow: { type: "number" }, temperatureHigh: { type: "number" },
          humidityLow: { type: "number" }, humidityHigh: { type: "number" },
          measurements: { type: "object", additionalProperties: { type: "object", required: ["value", "low", "high"], properties: { value: { type: "number" }, low: { type: "number" }, high: { type: "number" } } } },
        },
      },
      HistorySeries: {
        type: "object",
        required: ["sensorId", "readings", "forecast"],
        properties: {
          sensorId: { type: "string" }, readings: { type: "array", items: { $ref: "#/components/schemas/Reading" } },
          forecast: { type: "array", items: { $ref: "#/components/schemas/ForecastPoint" } },
        },
      },
      Point: {
        type: "object",
        required: ["x", "y"],
        properties: {
          x: { type: "number", description: "Horizontal coordinate in the floor plan's width coordinate system." },
          y: { type: "number", description: "Depth coordinate in the floor plan's height coordinate system." },
        },
      },
      HouseLocation: {
        type: "object",
        description: "House position in the WGS84 latitude/longitude coordinate reference system. This is outdoor-context metadata, separate from floor-local x/y/z coordinates.",
        required: ["latitude", "longitude"],
        properties: {
          latitude: { type: "number", minimum: -90, maximum: 90, description: "WGS84 latitude in decimal degrees." },
          longitude: { type: "number", minimum: -180, maximum: 180, description: "WGS84 longitude in decimal degrees." },
          label: { type: "string", maxLength: 200, description: "Optional user-facing area label. A precise street address is not required." },
          countryCode: { type: "string", pattern: "^[A-Z]{2}$", description: "Optional ISO country hint retained from discovery." },
          source: { enum: ["manual", "place-search", "browser-geolocation", "home-assistant", "map-placement"] },
          confidence: { enum: ["high", "medium", "low"] },
          discoveredAt: { type: "string", format: "date-time" },
          userOverridden: { type: "boolean", description: "True after a person explicitly enters or corrects this value." },
        },
      },
      HouseMapPlacement: {
        type: "object",
        description: "Precise WGS84 placement and scale for drawing a floor plan on a map. This is independent of HouseLocation, which remains the weather lookup location.",
        required: ["latitude", "longitude", "metersPerPlanUnit"],
        properties: {
          latitude: { type: "number", minimum: -90, maximum: 90, description: "WGS84 latitude of the floor-plan anchor in decimal degrees." },
          longitude: { type: "number", minimum: -180, maximum: 180, description: "WGS84 longitude of the floor-plan anchor in decimal degrees." },
          metersPerPlanUnit: { type: "number", exclusiveMinimum: 0, description: "Real-world metres represented by one local floor-plan x/y unit." },
          footprintFloorId: { type: "string", minLength: 1, description: "Optional id of the house floor whose plan extent is used as the map footprint." },
        },
      },
      Floor: {
        type: "object",
        required: ["id", "name", "width", "height", "elevation", "walls", "rooms"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          type: { type: "string", enum: ["basement", "ground", "upper", "attic", "mezzanine", "outdoor"], description: "Semantic level type used by floor-management interfaces." },
          width: { type: "number", exclusiveMinimum: 0 },
          height: { type: "number", exclusiveMinimum: 0 },
          elevation: { type: "number", description: "Absolute floor-plane height in metres in the house vertical coordinate system; sensor z values use the same vertical origin." },
          ceilingHeight: { type: "number", exclusiveMinimum: 0, description: "Clear room height in metres." },
          walls: { type: "array", items: { type: "object", required: ["id", "from", "to"], properties: { id: { type: "string" }, from: { $ref: "#/components/schemas/Point" }, to: { $ref: "#/components/schemas/Point" } } } },
          rooms: { type: "array", items: { type: "object", required: ["id", "name", "points"], properties: { id: { type: "string" }, name: { type: "string" }, kind: { type: "string" }, points: { type: "array", minItems: 3, items: { $ref: "#/components/schemas/Point" } } } } },
          planElements: {
            type: "array",
            description: "Optional architectural symbols placed on the editable floor plan.",
            items: {
              oneOf: [
                {
                  title: "Wall opening",
                  type: "object",
                  required: ["id", "kind", "position", "rotationDegrees", "wallId"],
                  properties: {
                    id: { type: "string" },
                    kind: { type: "string", enum: ["door", "window"] },
                    position: { $ref: "#/components/schemas/Point" },
                    rotationDegrees: { type: "number", minimum: 0, exclusiveMaximum: 360 },
                    width: { type: "number", exclusiveMinimum: 0, description: "When present, the full width must fit within the referenced wall segment." },
                    wallId: { type: "string", description: "Required wall attachment used for alignment and cascade deletion." },
                  },
                },
                {
                  title: "Free-standing fixture",
                  type: "object",
                  required: ["id", "kind", "position", "rotationDegrees"],
                  not: { required: ["wallId"] },
                  properties: {
                    id: { type: "string" },
                    kind: { type: "string", enum: ["fireplace", "vent"] },
                    position: { $ref: "#/components/schemas/Point" },
                    rotationDegrees: { type: "number", minimum: 0, exclusiveMaximum: 360 },
                    width: { type: "number", exclusiveMinimum: 0 },
                  },
                },
              ],
            },
          },
          backgroundImage: { type: "string", description: "Optional trusted raster data URL used by the local floor-plan editor." },
        },
      },
      House: {
        type: "object",
        required: ["id", "name", "timezone", "floors", "createdAt", "updatedAt"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          timezone: { type: "string", description: "Timezone used for display and calendar grouping. New writes are validated as IANA time-zone identifiers; reads may expose an invalid historical value until it is corrected. Weather timestamps remain UTC ISO 8601." },
          location: { $ref: "#/components/schemas/HouseLocation" },
          mapPlacement: { $ref: "#/components/schemas/HouseMapPlacement" },
          orientationDegrees: { type: "number", minimum: 0, exclusiveMaximum: 360, description: "Confirmed clockwise compass bearing of the floor plan's top/up direction: 0=north, 90=east, 180=south, 270=west. Omitted while unknown." },
          floors: { type: "array", items: { $ref: "#/components/schemas/Floor" } },
          createdAt: { type: "string", format: "date-time", readOnly: true },
          updatedAt: { type: "string", format: "date-time", readOnly: true },
        },
      },
      HouseCreate: {
        type: "object",
        required: ["name", "timezone", "floors"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          timezone: { type: "string", maxLength: 100, description: "IANA time-zone identifier validated by the server." },
          location: { $ref: "#/components/schemas/HouseLocation" },
          mapPlacement: { $ref: "#/components/schemas/HouseMapPlacement" },
          orientationDegrees: { type: "number", minimum: 0, exclusiveMaximum: 360, description: "Confirmed clockwise compass bearing of the floor plan's top/up direction. Omit while unknown." },
          floors: { type: "array", items: { $ref: "#/components/schemas/Floor" } },
        },
      },
      HousePatch: {
        type: "object",
        description: "Partial house update. Use location: null to remove weather metadata and mapPlacement: null to remove precise map placement.",
        properties: {
          name: { type: "string" },
          timezone: { type: "string", maxLength: 100, description: "IANA time-zone identifier validated by the server when changed. An unchanged invalid historical value may be preserved." },
          location: { oneOf: [{ $ref: "#/components/schemas/HouseLocation" }, { type: "null" }] },
          mapPlacement: { oneOf: [{ $ref: "#/components/schemas/HouseMapPlacement" }, { type: "null" }] },
          orientationDegrees: { oneOf: [{ type: "number", minimum: 0, exclusiveMaximum: 360 }, { type: "null" }], description: "Confirmed clockwise compass bearing of the floor plan's top/up direction. Set null to return to unknown." },
          floors: { type: "array", items: { $ref: "#/components/schemas/Floor" } },
        },
      },
      OutdoorConditions: {
        type: "object",
        description: "Canonical outdoor observation or forecast values. Properties absent from the FMI response are omitted rather than inferred or converted to zero.",
        required: ["timestamp"],
        properties: {
          timestamp: { type: "string", format: "date-time" },
          temperatureC: { type: "number", description: "Air temperature in degrees Celsius." },
          dewPointC: { type: "number", description: "Dew point in degrees Celsius." },
          relativeHumidityPercent: { type: "number", description: "Relative humidity in percent." },
          pressureHpa: { type: "number", description: "Sea-level pressure in hectopascals." },
          windDirectionDegrees: { type: "number", description: "Wind direction in degrees." },
          windSpeedMps: { type: "number", description: "Wind speed in metres per second." },
          windGustMps: { type: "number", description: "Wind gust in metres per second." },
          precipitation1hMm: { type: "number", description: "One-hour precipitation in millimetres." },
          precipitationIntensityMmPerHour: { type: "number", description: "Observed precipitation intensity in millimetres per hour." },
          precipitationProbabilityPercent: { type: "number" },
          precipitationFormCode: { type: "number", description: "FMI precipitation-form code; clients must use FMI code metadata rather than invent labels." },
          potentialPrecipitationFormCode: { type: "number", description: "FMI potential precipitation-form code." },
          snowDepthCm: { type: "number", description: "Observed snow depth in centimetres." },
          cloudCoverPercent: { type: "number" },
          lowCloudCoverPercent: { type: "number" },
          mediumCloudCoverPercent: { type: "number" },
          highCloudCoverPercent: { type: "number" },
          visibilityMeters: { type: "number" },
          fogIntensity: { type: "number", description: "FMI fog-intensity value." },
          globalRadiationWm2: { type: "number", description: "Global solar radiation in watts per square metre." },
          weatherSymbolCode: { type: "number", description: "FMI WeatherSymbol3 code." },
          presentWeatherCode: { type: "number", description: "Observed FMI/WMO present-weather code." },
          thunderstormProbabilityPercent: { type: "number" },
          frostProbabilityPercent: { type: "number" },
          severeFrostProbabilityPercent: { type: "number" },
          maximumWindSpeedMps: { type: "number", description: "Hourly maximum wind speed in metres per second." },
          maximumWindGustMps: { type: "number", description: "Hourly maximum gust in metres per second." },
        },
      },
      WeatherStation: {
        type: "object",
        description: "Provenance for the nearest recent FMI observation station selected by the service. It is not the house position.",
        required: ["id", "name", "latitude", "longitude", "distanceKm"],
        properties: {
          id: { type: ["string", "null"] },
          name: { type: "string" },
          latitude: { type: "number" },
          longitude: { type: "number" },
          distanceKm: { type: "number", minimum: 0 },
        },
      },
      WeatherWarning: {
        type: "object",
        description: "An actual, non-cancelled FMI CAP warning whose polygon or circle contains the stored house location.",
        required: ["id", "event", "headline", "description", "severity", "urgency", "certainty", "effectiveAt", "onsetAt", "expiresAt", "areas", "web"],
        properties: {
          id: { type: "string" },
          event: { type: "string" },
          headline: { type: "string" },
          description: { type: "string" },
          severity: { enum: ["minor", "moderate", "severe", "extreme", "unknown"] },
          urgency: { type: "string" },
          certainty: { type: "string" },
          effectiveAt: { type: ["string", "null"], format: "date-time" },
          onsetAt: { type: ["string", "null"], format: "date-time" },
          expiresAt: { type: ["string", "null"], format: "date-time" },
          areas: { type: "array", items: { type: "string" } },
          web: { type: ["string", "null"], format: "uri" },
        },
      },
      WeatherComponentStatus: {
        type: "object",
        description: "Provider-neutral availability, coverage, freshness, and provenance for one weather component.",
        required: ["provider", "product", "attribution", "availability", "coverage", "emptyResultIsAuthoritative", "fetchedAt", "stale"],
        properties: {
          provider: { type: "string", enum: ["fmi", "open-meteo"] },
          product: { type: "string", description: "Provider product, endpoint, or dataset identifier." },
          attribution: { type: "string" },
          availability: { type: "string", enum: ["available", "unavailable", "not-applicable"] },
          coverage: { type: "string", enum: ["covered", "outside-coverage", "unknown"] },
          emptyResultIsAuthoritative: { type: "boolean", description: "True only when an empty value from this component authoritatively means none exists for the location and time." },
          fetchedAt: { type: "string", format: "date-time" },
          stale: { type: "boolean" },
        },
      },
      LocationSuggestion: {
        type: "object",
        required: ["id", "name", "label", "latitude", "longitude", "timezone", "countryCode", "country", "region", "source", "confidence"],
        properties: {
          id: { type: "string" }, name: { type: "string" }, label: { type: "string" },
          latitude: { type: "number", minimum: -90, maximum: 90 }, longitude: { type: "number", minimum: -180, maximum: 180 },
          timezone: { type: "string", description: "IANA timezone supplied by the place database." },
          countryCode: { type: ["string", "null"] }, country: { type: ["string", "null"] }, region: { type: ["string", "null"] },
          source: { const: "open-meteo-geocoding" }, confidence: { enum: ["high", "medium"] },
        },
      },
      CoordinateDefaults: {
        type: "object",
        required: ["timezone", "source"],
        properties: {
          timezone: { type: "string", description: "IANA timezone resolved for the supplied coordinates." },
          source: { const: "open-meteo-coordinate" },
        },
      },
      WeatherComponentStatuses: {
        type: "object",
        required: ["observation", "forecast", "short-range", "warnings"],
        properties: {
          observation: { $ref: "#/components/schemas/WeatherComponentStatus" },
          forecast: { $ref: "#/components/schemas/WeatherComponentStatus" },
          "short-range": { $ref: "#/components/schemas/WeatherComponentStatus" },
          warnings: { $ref: "#/components/schemas/WeatherComponentStatus" },
        },
      },
      HouseWeather: {
        type: "object",
        description: "House-scoped observation, point forecast, and official-warning context. Inspect provenance, stale, componentStatus, and unavailable before decisions.",
        required: ["houseId", "location", "provider", "attribution", "fetchedAt", "forecastIssuedAt", "stale", "current", "observationStation", "forecast", "warnings", "unavailable"],
        properties: {
          houseId: { type: "string" },
          location: { $ref: "#/components/schemas/HouseLocation" },
          provider: { type: "string", enum: ["fmi", "open-meteo"] },
          attribution: { type: "string", description: "Required provider attribution; preserve it in displays and downstream exports." },
          fetchedAt: { type: "string", format: "date-time", description: "Time the upstream fetch represented by this object began." },
          forecastIssuedAt: { type: ["string", "null"], format: "date-time", description: "FMI result time for the edited forecast, when available." },
          stale: { type: "boolean", description: "True when an upstream refresh failed and the service returned its previous in-memory result." },
          current: { oneOf: [{ $ref: "#/components/schemas/OutdoorConditions" }, { type: "null" }] },
          observationStation: { oneOf: [{ $ref: "#/components/schemas/WeatherStation" }, { type: "null" }] },
          forecast: { type: "array", items: { $ref: "#/components/schemas/OutdoorConditions" } },
          warnings: { type: "array", items: { $ref: "#/components/schemas/WeatherWarning" } },
          unavailable: { type: "array", uniqueItems: true, items: { enum: ["observation", "forecast", "short-range", "warnings"] }, description: "Legacy compatibility field listing upstream components that failed, returned no usable values, or do not cover this location. Prefer componentStatus when present." },
          componentStatus: { $ref: "#/components/schemas/WeatherComponentStatuses" },
        },
      },
      ThermalModelV1: {
        type: "object",
        description: "Effective first-order lumped model. Its fitted parameters are empirical and must not be interpreted as wall U-values, leakage, or material properties.",
        required: ["method", "version", "scope", "trainedFrom", "trainedTo", "parameters", "applicability", "sensitivity"],
        properties: {
          method: { const: "first-order-lumped-v1" },
          version: { const: "1.0.0" },
          scope: { type: "object", required: ["houseId", "sensorIds"], properties: { houseId: { type: "string" }, sensorIds: { type: "array", items: { type: "string" } } } },
          trainedFrom: { type: "string", format: "date-time" },
          trainedTo: { type: "string", format: "date-time" },
          parameters: { type: "object", required: ["timeConstantHours", "effectiveEquilibriumLiftC"], properties: { timeConstantHours: { type: "number" }, effectiveEquilibriumLiftC: { type: "number" } } },
          applicability: { type: "object", additionalProperties: { type: "number" } },
          sensitivity: { type: "object", additionalProperties: { type: "number" } },
        },
      },
      ThermalSimulationPoint: {
        type: "object",
        required: ["timestamp", "phase", "outdoorTemperatureC", "observedTemperatureC", "simulatedTemperatureC", "residualC", "lowC", "highC"],
        properties: {
          timestamp: { type: "string", format: "date-time" },
          phase: { enum: ["fit", "scenario"] },
          outdoorTemperatureC: { type: "number" },
          observedTemperatureC: { type: ["number", "null"] },
          simulatedTemperatureC: { type: "number" },
          residualC: { type: ["number", "null"], description: "Observed minus simulated temperature." },
          lowC: { type: "number", description: "Lower empirical model band; not a formal confidence interval." },
          highC: { type: "number", description: "Upper empirical model band; not a formal confidence interval." },
        },
      },
      ThermalSimulationResult: {
        type: "object",
        required: ["generatedAt", "systemVersion", "houseId", "sensorId", "roomLabel", "from", "to", "horizonHours", "scenarioOutdoorTemperatureC", "scenarioAnchorTimestamp", "calibration", "points"],
        properties: {
          generatedAt: { type: "string", format: "date-time" },
          systemVersion: { type: "string" },
          houseId: { type: "string" },
          sensorId: { type: "string" },
          roomLabel: { type: "string" },
          from: { type: "string", format: "date-time" },
          to: { type: "string", format: "date-time" },
          horizonHours: { type: "integer" },
          scenarioOutdoorTemperatureC: { type: ["number", "null"] },
          scenarioAnchorTimestamp: { type: ["string", "null"], format: "date-time" },
          calibration: {
            type: "object",
            required: ["status", "model", "quality", "warnings", "assumptions"],
            properties: {
              status: { enum: ["ready", "provisional", "insufficient-data"] },
              model: { oneOf: [{ $ref: "#/components/schemas/ThermalModelV1" }, { type: "null" }] },
              quality: { type: "object", additionalProperties: true },
              warnings: { type: "array", items: { type: "string" } },
              assumptions: { type: "array", items: { type: "string" } },
            },
          },
          points: { type: "array", items: { $ref: "#/components/schemas/ThermalSimulationPoint" } },
        },
      },
      Sensor: {
        type: "object",
        required: ["id", "houseId", "floorId", "name", "room", "model", "x", "y", "z", "tags", "enabled"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" }, floorId: { type: "string" },
          name: { type: "string" }, room: { type: "string" }, model: { type: "string" },
          x: { type: "number" }, y: { type: "number" }, z: { type: "number" },
          temperatureEntityId: { type: "string" }, humidityEntityId: { type: "string" }, batteryEntityId: { type: "string" },
          tpLinkDeviceId: { type: "string" }, measurementEntityIds: { type: "object", additionalProperties: { type: "string" } },
          tags: { type: "array", items: { type: "string" } }, enabled: { type: "boolean" },
        },
      },
      SensorSnapshot: {
        allOf: [
          { $ref: "#/components/schemas/Sensor" },
          { type: "object", required: ["reading"], properties: { reading: { oneOf: [{ $ref: "#/components/schemas/Reading" }, { type: "null" }] } } },
        ],
      },
      SensorInput: {
        type: "object",
        required: ["houseId", "floorId", "name", "room", "model", "x", "y", "z"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" }, floorId: { type: "string" },
          name: { type: "string" }, room: { type: "string" }, model: { type: "string" },
          x: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the selected floor width." },
          y: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the selected floor height." },
          z: { type: "number", description: "Unbounded absolute sensor height in metres using the same vertical origin as Floor.elevation; it may be below or above the floor plane." },
          tags: { type: "array", items: { type: "string" } }, enabled: { type: "boolean", default: true },
          temperatureEntityId: { type: "string" }, humidityEntityId: { type: "string" }, batteryEntityId: { type: "string" },
          tpLinkDeviceId: { oneOf: [{ type: "string" }, { type: "null" }], description: "Stable direct-hub child-device identifier. It must be unique when present." },
          measurementEntityIds: { type: "object", additionalProperties: { type: "string" } },
        },
      },
      SensorPatch: {
        type: "object",
        description: "Partial sensor update. A house/floor move and its coordinates are validated together before one atomic update.",
        properties: {
          houseId: { type: "string" }, floorId: { type: "string" },
          name: { type: "string" }, room: { type: "string" }, model: { type: "string" },
          x: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the resulting floor width." },
          y: { type: "number", minimum: 0, description: "Floor-local position; must be less than or equal to the resulting floor height." },
          z: { type: "number", description: "Unbounded absolute height in metres; negative and above-floor values are valid." },
          tags: { type: "array", items: { type: "string" } }, enabled: { type: "boolean" },
          temperatureEntityId: { type: "string" }, humidityEntityId: { type: "string" }, batteryEntityId: { type: "string" },
          tpLinkDeviceId: { oneOf: [{ type: "string" }, { type: "null" }], description: "Assign a direct TP-Link child device, or set null to clear the binding." },
          measurementEntityIds: { type: "object", additionalProperties: { type: "string" } },
        },
      },
      AlertRuleInput: {
        type: "object",
        required: ["name", "metric", "operator", "threshold", "durationSeconds", "severity"],
        properties: {
          id: { type: "string" }, name: { type: "string" }, sensorId: { type: ["string", "null"], default: null },
          metric: { type: "string" }, operator: { enum: ["gt", "gte", "lt", "lte"] }, threshold: { type: "number" },
          durationSeconds: { type: "integer", minimum: 1, maximum: 31536000 },
          severity: { enum: ["info", "warning", "critical"] }, enabled: { type: "boolean", default: true },
          webhookEnabled: { type: "boolean", default: false },
        },
      },
      AlertRule: {
        type: "object",
        required: ["id", "name", "sensorId", "metric", "operator", "threshold", "durationSeconds", "severity", "enabled", "webhookEnabled"],
        properties: {
          id: { type: "string" }, name: { type: "string" }, sensorId: { type: ["string", "null"] }, metric: { type: "string" },
          operator: { enum: ["gt", "gte", "lt", "lte"] }, threshold: { type: "number" }, durationSeconds: { type: "integer", minimum: 1, maximum: 31536000 },
          severity: { enum: ["info", "warning", "critical"] }, enabled: { type: "boolean" }, webhookEnabled: { type: "boolean" },
        },
      },
      AlertRulePatch: {
        type: "object",
        properties: {
          name: { type: "string" }, sensorId: { type: ["string", "null"] }, metric: { type: "string" },
          operator: { enum: ["gt", "gte", "lt", "lte"] }, threshold: { type: "number" },
          durationSeconds: { type: "integer", minimum: 1, maximum: 31536000 },
          severity: { enum: ["info", "warning", "critical"] }, enabled: { type: "boolean" }, webhookEnabled: { type: "boolean" },
        },
      },
      AlertEvent: {
        type: "object",
        required: ["id", "ruleId", "sensorId", "metric", "value", "threshold", "severity", "startedAt", "acknowledgedAt", "resolvedAt"],
        properties: {
          id: { type: "string" }, ruleId: { type: "string" }, sensorId: { type: "string" }, metric: { type: "string" },
          value: { type: "number" }, threshold: { type: "number" }, severity: { enum: ["info", "warning", "critical"] },
          startedAt: { type: "string", format: "date-time" }, acknowledgedAt: { type: ["string", "null"], format: "date-time" },
          resolvedAt: { type: ["string", "null"], format: "date-time" },
        },
      },
      ObservationInput: {
        type: "object",
        required: ["houseId", "floorId", "kind", "severity", "note"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" }, floorId: { type: "string" }, sensorId: { type: ["string", "null"] },
          kind: { enum: ["leak", "condensation", "mould", "ventilation", "maintenance", "note"] },
          severity: { enum: ["info", "warning", "critical"] }, note: { type: "string" },
          x: { type: ["number", "null"] }, y: { type: ["number", "null"] },
          occurredAt: { type: "string", format: "date-time", description: "Defaults to the server time." },
        },
      },
      ManualObservation: {
        type: "object",
        required: ["id", "houseId", "floorId", "sensorId", "kind", "severity", "note", "x", "y", "occurredAt", "createdAt"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" }, floorId: { type: "string" }, sensorId: { type: ["string", "null"] },
          kind: { enum: ["leak", "condensation", "mould", "ventilation", "maintenance", "note"] },
          severity: { enum: ["info", "warning", "critical"] }, note: { type: "string" },
          x: { type: ["number", "null"] }, y: { type: ["number", "null"] },
          occurredAt: { type: "string", format: "date-time" }, createdAt: { type: "string", format: "date-time" },
        },
      },
      StaticParameterInput: {
        type: "object",
        required: ["houseId", "scopeType", "scopeId", "key", "value", "label"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" },
          scopeType: { enum: ["house", "floor", "room", "sensor"] }, scopeId: { type: "string" }, key: { type: "string" },
          value: { oneOf: [{ type: "string" }, { type: "number" }, { type: "boolean" }] },
          unit: { type: ["string", "null"], default: null }, label: { type: "string" },
        },
      },
      StaticParameter: {
        type: "object",
        required: ["id", "houseId", "scopeType", "scopeId", "key", "value", "unit", "label"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" }, scopeType: { enum: ["house", "floor", "room", "sensor"] },
          scopeId: { type: "string" }, key: { type: "string" },
          value: { oneOf: [{ type: "string" }, { type: "number" }, { type: "boolean" }] }, unit: { type: ["string", "null"] }, label: { type: "string" },
        },
      },
      AssetUploadInput: {
        type: "object",
        required: ["houseId", "name", "mimeType", "kind", "data"],
        properties: {
          houseId: { type: "string" }, name: { type: "string" },
          mimeType: { enum: ["image/png", "image/jpeg", "image/webp", "model/gltf+json", "model/gltf-binary"] },
          kind: { enum: ["floor-plan", "model-3d", "other"] },
          data: { type: "string", description: "Base64 bytes, optionally prefixed by a data URL; decoded content is limited to 10 MiB." },
        },
      },
      Asset: {
        type: "object",
        required: ["id", "houseId", "name", "mimeType", "kind", "size", "createdAt"],
        properties: {
          id: { type: "string" }, houseId: { type: "string" }, name: { type: "string" }, mimeType: { type: "string" },
          kind: { enum: ["floor-plan", "model-3d", "other"] }, size: { type: "integer", minimum: 0 }, createdAt: { type: "string", format: "date-time" },
        },
      },
      HomeAssistantConfigInput: {
        type: "object",
        required: ["url", "token"],
        properties: {
          url: { type: "string", format: "uri", maxLength: 2048, description: "HTTP(S) Home Assistant address without embedded credentials." },
          token: { type: "string", minLength: 1, maxLength: 8192, writeOnly: true },
        },
      },
      TpLinkConfigInput: {
        type: "object",
        required: ["host", "username", "password"],
        properties: {
          host: { type: "string", minLength: 1, maxLength: 253 },
          username: { type: "string", minLength: 1, maxLength: 320, writeOnly: true },
          password: { type: "string", minLength: 1, maxLength: 4096, writeOnly: true },
        },
      },
      IntegrationStatus: {
        type: "object",
        required: ["homeAssistant", "tpLink", "webhook", "mock", "weather"],
        properties: {
          homeAssistant: { type: "object", required: ["configured", "connected", "lastEventAt", "mappedEntities", "error"], properties: { configured: { type: "boolean" }, connected: { type: "boolean" }, lastEventAt: { type: ["string", "null"], format: "date-time" }, mappedEntities: { type: "integer" }, error: { type: ["string", "null"] } } },
          tpLink: { type: "object", required: ["configured", "connected", "lastPollAt", "mappedDevices", "discoveredDevices", "hubModel", "error"], properties: { configured: { type: "boolean" }, connected: { type: "boolean" }, lastPollAt: { type: ["string", "null"], format: "date-time" }, mappedDevices: { type: "integer" }, discoveredDevices: { type: "integer" }, hubModel: { enum: ["H100", "H200", null] }, error: { type: ["string", "null"] } } },
          webhook: { type: "object", required: ["configured", "lastDeliveryAt", "error"], properties: { configured: { type: "boolean" }, lastDeliveryAt: { type: ["string", "null"], format: "date-time" }, error: { type: ["string", "null"] } } },
          mock: { type: "object", required: ["enabled", "intervalMs", "mode", "activatedAt"], properties: { enabled: { type: "boolean" }, intervalMs: { type: "integer" }, mode: { enum: ["demo", "real"] }, activatedAt: { type: ["string", "null"], format: "date-time" } } },
          weather: { type: "object", required: ["provider", "configuredHouses", "lastSuccessAt", "error"], properties: { policy: { enum: ["automatic", "fmi", "open-meteo"] }, availableProviders: { type: "array", items: { enum: ["fmi", "open-meteo"] } }, provider: { enum: ["fmi", "open-meteo"] }, configuredHouses: { type: "integer" }, lastSuccessAt: { type: ["string", "null"], format: "date-time" }, error: { type: ["string", "null"] } } },
        },
      },
      IntegrationDiscoveryResult: {
        type: "object",
        required: ["homeAssistant", "tpLink", "warnings"],
        properties: {
          homeAssistant: { type: "array", items: { type: "object", required: ["name", "url", "host", "port", "version"], properties: { name: { type: "string" }, url: { type: "string", format: "uri" }, host: { type: "string" }, port: { type: "integer" }, version: { type: ["string", "null"] } } } },
          tpLink: { type: "array", items: { type: "object", required: ["host", "model", "alias"], properties: { host: { type: "string" }, model: { enum: ["H100", "H200"] }, alias: { type: ["string", "null"] } } } },
          warnings: { type: "array", items: { type: "string" } },
        },
      },
      IntegrationTestResult: { type: "object", required: ["ok", "message"], properties: { ok: { type: "boolean" }, message: { type: "string" } } },
      MockScenarioId: { type: "string", enum: ["normal", "shower", "leak", "cold-front", "heating-failure"] },
      MockScenario: {
        type: "object",
        required: ["id", "label", "description"],
        properties: { id: { $ref: "#/components/schemas/MockScenarioId" }, label: { type: "string" }, description: { type: "string" } },
      },
      ReplayInput: {
        type: "object",
        properties: {
          sensorIds: { type: "array", items: { type: "string" }, description: "Defaults to every configured sensor." },
          from: { type: "string", format: "date-time", description: "Defaults to one hour before to." },
          to: { type: "string", format: "date-time", description: "Defaults to the server time." },
          speed: { type: "number", minimum: 0.1, maximum: 10000, default: 60 },
        },
      },
      ReplayState: {
        type: "object",
        required: ["active", "count", "emitted", "speed", "from", "to"],
        properties: {
          active: { type: "boolean" }, count: { type: "integer" }, emitted: { type: "integer" }, speed: { type: "number" },
          from: { type: ["string", "null"], format: "date-time" }, to: { type: ["string", "null"], format: "date-time" },
        },
      },
      TpLinkDiscoveredDevice: {
        type: "object",
        required: ["deviceId", "model", "alias", "status", "temperature", "humidity", "battery", "lastSeenAt", "mappedSensorId"],
        properties: {
          deviceId: { type: "string" },
          model: { type: "string" },
          alias: { oneOf: [{ type: "string" }, { type: "null" }] },
          status: { oneOf: [{ type: "string" }, { type: "null" }] },
          temperature: { oneOf: [{ type: "number" }, { type: "null" }], description: "Temperature normalized to degrees Celsius." },
          humidity: { oneOf: [{ type: "number" }, { type: "null" }] },
          battery: { oneOf: [{ type: "number" }, { type: "null" }] },
          lastSeenAt: { type: "string", format: "date-time" },
          mappedSensorId: { oneOf: [{ type: "string" }, { type: "null" }] },
        },
      },
    },
    responses: {
      NotFound: { description: "Resource not found" },
    },
  },
} as const;

const V2_PATHS = new Set([
  "/measurement-definitions",
  "/measurement-definitions/{id}",
  "/measurements",
  "/measurements/import",
  "/measurements/snapshot",
  "/measurements/history",
  "/measurements/events",
  "/measurements/forecast",
]);

function selectPaths(version: "v1" | "v2"): Record<string, unknown> {
  return Object.fromEntries(Object.entries(combinedOpenApiDocument.paths).filter(([path]) =>
    path === "/openapi.json" || (version === "v2" ? V2_PATHS.has(path) : !V2_PATHS.has(path))));
}

export const openApiV1Document = {
  ...combinedOpenApiDocument,
  info: { ...combinedOpenApiDocument.info, version: "1.0.0", description: "Stuga v1 compatibility API for layouts, house-scoped FMI weather, and temperature/humidity tuples." },
  servers: [{ url: "/api/v1", description: "Legacy climate tuple API" }],
  paths: selectPaths("v1"),
};

export const openApiV2Document = {
  ...combinedOpenApiDocument,
  info: { ...combinedOpenApiDocument.info, version: "2.0.0", description: "Stuga v2 registry-driven sparse measurements API." },
  servers: [{ url: "/api/v2", description: "Registry-driven measurements API" }],
  paths: selectPaths("v2"),
};

/** @deprecated Import the version-specific document. Retained for source compatibility. */
export const openApiDocument = openApiV1Document;
